use crate::runtime;

pub(crate) fn dispatch(command: runtime::Command) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Merge {
            abort,
            continue_,
            ff_only,
            no_ff,
            no_commit,
            squash,
            strategies,
            commits,
        } => runtime::merge_commands::merge(runtime::merge_commands::MergeOptions {
            abort,
            continue_,
            ff_only,
            no_ff,
            no_commit,
            squash,
            strategies,
            commits,
        }),
        runtime::Command::Mergetool {
            tool,
            no_prompt: _,
            prompt: _,
            paths,
        } => runtime::merge_commands::mergetool(tool.as_deref(), paths),
        runtime::Command::MergeTree {
            write_tree,
            trivial_merge,
            messages,
            no_messages,
            quiet,
            nul_terminated,
            name_only,
            allow_unrelated_histories,
            stdin,
            merge_base,
            strategy_options,
            args,
        } => runtime::merge_commands::merge_tree_command(runtime::MergeTreeOptions {
            write_tree,
            trivial_merge,
            messages,
            no_messages,
            quiet,
            nul_terminated,
            name_only,
            allow_unrelated_histories,
            stdin,
            merge_base,
            strategy_options,
            args,
        }),
        runtime::Command::MergeFile {
            stdout,
            labels,
            current,
            base,
            other,
        } => runtime::merge_commands::merge_file_command(stdout, labels, current, base, other),
        runtime::Command::MergeOneFile {
            orig_blob,
            our_blob,
            their_blob,
            path,
            orig_mode,
            our_mode,
            their_mode,
        } => runtime::merge_commands::merge_one_file(
            &orig_blob,
            &our_blob,
            &their_blob,
            &path,
            &orig_mode,
            &our_mode,
            &their_mode,
        ),
        runtime::Command::MergeIndex {
            one_shot,
            quiet,
            merge_program,
            all,
            paths,
        } => runtime::merge_commands::merge_index(one_shot, quiet, &merge_program, all, paths),
        command => unreachable!("non-merge command routed to merge dispatcher: {command:?}"),
    }
}
