use crate::runtime;

pub(crate) fn dispatch(command: runtime::Command) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Commit {
            all,
            only,
            allow_empty,
            amend,
            edit,
            no_edit,
            signoff,
            quiet,
            verbose,
            no_verify,
            status,
            no_status,
            cleanup,
            no_cleanup,
            allow_empty_message,
            author,
            date,
            squash,
            template,
            reset_author,
            reuse_message,
            reedit_message,
            fixup,
            message_file,
            messages,
            trailers,
            paths,
        } => super::commit_commands::commit_command(super::commit_commands::CommitCommandOptions {
            all,
            only,
            allow_empty,
            amend,
            edit,
            no_edit,
            signoff,
            quiet,
            verbose,
            no_verify,
            status,
            no_status,
            cleanup: cleanup.as_deref(),
            no_cleanup,
            allow_empty_message,
            author_override: author.as_deref(),
            date_override: date.as_deref(),
            squash: squash.as_deref(),
            template: template.as_deref(),
            reset_author,
            reuse_message: reuse_message.as_deref(),
            reedit_message: reedit_message.as_deref(),
            fixup: fixup.as_deref(),
            message_file: message_file.as_deref(),
            messages,
            trailers,
            paths,
        }),
        runtime::Command::Citool {
            amend,
            nocommit,
            message_file,
            messages,
        } => super::commit_commands::citool_command(
            amend,
            nocommit,
            message_file.as_deref(),
            messages,
        ),
        runtime::Command::Gui { args } => super::commit_commands::gui_command(args),
        runtime::Command::WriteTree { prefix, missing_ok } => {
            super::commit_commands::write_tree_command_entry(prefix.as_deref(), missing_ok)
        }
        runtime::Command::CommitTree {
            tree,
            parents,
            messages,
        } => super::commit_commands::commit_tree_command(&tree, parents, messages),
        runtime::Command::Mktree {
            nul_terminated,
            missing,
            batch,
        } => super::commit_commands::mktree_command(nul_terminated, missing, batch),
        _ => unreachable!("non-commit command dispatched to commit"),
    }
}
