use std::path::PathBuf;

use crate::runtime;

pub(crate) fn dispatch(command: runtime::Command) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Diff {
            no_index,
            recursive: _,
            nul_terminated,
            cached,
            base,
            ours,
            theirs,
            reverse,
            reverse_long: _,
            check,
            patch: _,
            patch_with_raw,
            patch_with_stat,
            no_patch,
            binary,
            stat,
            no_stat,
            compact_summary,
            numstat,
            shortstat,
            dirstat,
            cumulative,
            dirstat_by_file,
            raw,
            summary,
            name_status,
            name_only,
            find_renames,
            break_rewrites,
            irreversible_delete,
            submodule,
            ignore_submodules,
            find_copies,
            find_copies_harder,
            no_renames,
            rename_limit_short,
            merge,
            dense_combined,
            tree_in_diff,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            order_file,
            skip_to,
            rotate_to,
            diff_filter,
            word_diff,
            color_words,
            word_diff_regex,
            abbrev,
            no_abbrev,
            abbrev_commit: _,
            no_abbrev_commit: _,
            full_index,
            no_full_index,
            no_prefix,
            default_prefix,
            src_prefix,
            dst_prefix,
            relative,
            no_relative,
            unified,
            encoding: _,
            oneline: _,
            function_context,
            expand_tabs: _,
            no_expand_tabs: _,
            inter_hunk_context,
            minimal,
            patience,
            histogram,
            diff_algorithm,
            anchored,
            output_indicator_new,
            output_indicator_old,
            output_indicator_context,
            output: _,
            line_prefix,
            ignore_space_at_eol,
            ignore_cr_at_eol,
            ignore_space_change,
            ignore_all_space,
            ignore_blank_lines,
            ignore_matching_lines,
            no_ext_diff,
            ext_diff,
            no_textconv,
            textconv,
            text,
            color,
            no_color,
            color_moved,
            color_moved_ws,
            no_color_moved,
            no_color_moved_ws,
            indent_heuristic,
            no_indent_heuristic,
            rename_empty,
            no_rename_empty,
            ita_invisible_in_index,
            find_object,
            diff_merges,
            no_diff_merges,
            remerge_diff,
            combined_all_paths,
            dd,
            ws_error_highlight,
            quiet,
            exit_code,
            paths,
        } => {
            let (unified, paths) = normalize_porcelain_unified_operands(unified, paths);
            super::diff_commands::diff(runtime::DiffOptions {
                no_index,
                nul_terminated,
                cached,
                base,
                ours,
                theirs,
                reverse,
                check,
                patch_with_raw,
                patch_with_stat,
                stat,
                no_stat,
                compact_summary,
                no_patch,
                binary,
                numstat,
                shortstat,
                dirstat,
                cumulative,
                dirstat_by_file,
                raw,
                summary,
                name_status,
                name_only,
                find_renames,
                break_rewrites,
                irreversible_delete,
                submodule,
                ignore_submodules,
                find_copies,
                find_copies_harder,
                no_renames,
                rename_limit_short,
                merge,
                tree_in_diff,
                dense_combined,
                pickaxe_string,
                pickaxe_regex,
                pickaxe_regex_mode,
                pickaxe_all,
                order_file,
                skip_to,
                rotate_to,
                diff_filter,
                word_diff,
                color_words,
                word_diff_regex,
                abbrev,
                no_abbrev,
                full_index,
                no_full_index,
                no_prefix,
                default_prefix,
                src_prefix,
                dst_prefix,
                relative,
                no_relative,
                unified,
                function_context,
                inter_hunk_context,
                minimal,
                patience,
                histogram,
                diff_algorithm,
                anchored,
                output_indicator_new,
                output_indicator_old,
                output_indicator_context,
                line_prefix,
                ignore_space_at_eol,
                ignore_cr_at_eol,
                ignore_space_change,
                ignore_all_space,
                ignore_blank_lines,
                ignore_matching_lines,
                no_ext_diff,
                ext_diff,
                no_textconv,
                textconv,
                text,
                color,
                no_color,
                color_moved,
                color_moved_ws,
                no_color_moved,
                no_color_moved_ws,
                indent_heuristic,
                no_indent_heuristic,
                rename_empty,
                no_rename_empty,
                ita_invisible_in_index,
                find_object,
                diff_merges,
                no_diff_merges,
                remerge_diff,
                combined_all_paths,
                dd,
                ws_error_highlight,
                quiet,
                exit_code,
                paths,
            })
        }
        runtime::Command::Difftool {
            cached,
            dir_diff,
            tool,
            gui,
            no_gui,
            symlinks,
            no_symlinks,
            extcmd,
            no_prompt,
            prompt,
            tool_help,
            trust_exit_code,
            no_trust_exit_code,
            rotate_to,
            skip_to,
            paths,
        } => super::diff_commands::difftool(
            cached,
            dir_diff,
            tool.as_deref(),
            gui,
            no_gui,
            symlinks,
            no_symlinks,
            extcmd.as_deref(),
            no_prompt,
            prompt,
            tool_help,
            trust_exit_code,
            no_trust_exit_code,
            rotate_to.as_deref(),
            skip_to.as_deref(),
            paths,
        ),
        runtime::Command::DiffFiles {
            nul_terminated,
            patch,
            patch_with_raw,
            patch_with_stat,
            no_patch,
            binary,
            stat,
            no_stat,
            compact_summary,
            numstat,
            shortstat,
            check,
            dirstat,
            cumulative,
            dirstat_by_file,
            raw,
            summary,
            name_status,
            name_only,
            find_renames,
            break_rewrites,
            irreversible_delete,
            submodule,
            ignore_submodules,
            find_copies,
            find_copies_harder,
            omit_unmerged,
            base,
            ours,
            theirs,
            no_renames,
            rename_limit_short,
            merge,
            combined,
            dense_combined,
            tree_in_diff,
            reverse,
            reverse_long: _,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            order_file,
            skip_to,
            rotate_to,
            diff_filter,
            word_diff,
            color_words,
            word_diff_regex,
            abbrev,
            no_abbrev,
            abbrev_commit: _,
            no_abbrev_commit: _,
            full_index,
            no_full_index,
            no_prefix,
            default_prefix,
            src_prefix,
            dst_prefix,
            relative,
            no_relative,
            unified,
            encoding: _,
            oneline: _,
            function_context,
            expand_tabs: _,
            no_expand_tabs: _,
            inter_hunk_context,
            minimal,
            patience,
            histogram,
            diff_algorithm,
            anchored,
            output_indicator_new,
            output_indicator_old,
            output_indicator_context,
            output: _,
            line_prefix,
            ignore_space_at_eol,
            ignore_cr_at_eol,
            ignore_space_change,
            ignore_all_space,
            ignore_blank_lines,
            ignore_matching_lines,
            text,
            no_ext_diff,
            ext_diff,
            no_textconv,
            textconv,
            color,
            no_color,
            color_moved,
            color_moved_ws,
            no_color_moved,
            no_color_moved_ws,
            indent_heuristic,
            no_indent_heuristic,
            rename_empty,
            no_rename_empty,
            ita_invisible_in_index,
            find_object,
            diff_merges,
            no_diff_merges,
            remerge_diff,
            combined_all_paths,
            dd,
            ws_error_highlight,
            quiet,
            exit_code,
            quiet_unmerged: _,
            paths,
        } => super::diff_commands::diff_files(runtime::PlumbingDiffOptions {
            recursive: false,
            nul_terminated,
            patch,
            patch_with_raw,
            patch_with_stat,
            no_patch,
            binary,
            stat,
            no_stat,
            compact_summary,
            numstat,
            shortstat,
            check,
            dirstat,
            cumulative,
            dirstat_by_file,
            raw,
            summary,
            name_status,
            name_only,
            find_renames,
            break_rewrites,
            irreversible_delete,
            submodule,
            ignore_submodules,
            find_copies,
            find_copies_harder,
            omit_unmerged,
            base,
            ours,
            theirs,
            no_renames,
            rename_limit_short,
            merge,
            combined,
            dense_combined,
            tree_in_diff,
            reverse,
            root: false,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            order_file,
            skip_to,
            rotate_to,
            diff_filter,
            word_diff,
            color_words,
            word_diff_regex,
            abbrev: abbrev.last().cloned(),
            no_abbrev,
            abbrev_commit: false,
            no_abbrev_commit: false,
            full_index,
            no_full_index,
            no_prefix,
            default_prefix,
            src_prefix,
            dst_prefix,
            relative,
            no_relative,
            unified,
            encoding: None,
            oneline: false,
            function_context,
            expand_tabs: false,
            no_expand_tabs: false,
            inter_hunk_context,
            minimal,
            patience,
            histogram,
            diff_algorithm,
            anchored,
            output_indicator_new,
            output_indicator_old,
            output_indicator_context,
            line_prefix,
            ignore_space_at_eol,
            ignore_cr_at_eol,
            ignore_space_change,
            ignore_all_space,
            ignore_blank_lines,
            ignore_matching_lines,
            text,
            no_ext_diff,
            ext_diff,
            no_textconv,
            textconv,
            color,
            no_color,
            color_moved,
            color_moved_ws,
            no_color_moved,
            no_color_moved_ws,
            indent_heuristic,
            no_indent_heuristic,
            rename_empty,
            no_rename_empty,
            ita_invisible_in_index,
            merge_base: false,
            no_diff_merges,
            find_object,
            diff_merges,
            remerge_diff,
            combined_all_paths,
            dd,
            ws_error_highlight,
            no_notes: false,
            quiet,
            exit_code,
            pretty: None,
            notes: false,
            show_notes: false,
            show_notes_by_default: false,
            standard_notes: false,
            no_standard_notes: false,
            show_signature: false,
            no_commit_id: false,
            always: false,
            format: None,
            verbose: false,
            stdin: false,
            treeish: None,
            new_treeish: None,
            cached: false,
            paths,
        }),
        runtime::Command::DiffIndex {
            nul_terminated,
            cached,
            patch,
            patch_with_raw,
            patch_with_stat,
            no_patch,
            binary,
            stat,
            no_stat,
            compact_summary,
            numstat,
            shortstat,
            check,
            dirstat,
            cumulative,
            dirstat_by_file,
            raw,
            summary,
            name_status,
            name_only,
            find_renames,
            break_rewrites,
            irreversible_delete,
            submodule,
            ignore_submodules,
            find_copies,
            find_copies_harder,
            no_renames,
            rename_limit_short,
            merge,
            combined,
            dense_combined,
            tree_in_diff,
            reverse,
            reverse_long: _,
            root: _,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            order_file,
            skip_to,
            rotate_to,
            diff_filter,
            word_diff,
            color_words,
            word_diff_regex,
            abbrev,
            no_abbrev,
            abbrev_commit: _,
            no_abbrev_commit: _,
            full_index,
            no_full_index,
            no_prefix,
            default_prefix,
            src_prefix,
            dst_prefix,
            relative,
            no_relative,
            unified,
            encoding: _,
            oneline: _,
            function_context,
            expand_tabs: _,
            no_expand_tabs: _,
            inter_hunk_context,
            minimal,
            patience,
            histogram,
            diff_algorithm,
            anchored,
            output_indicator_new,
            output_indicator_old,
            output_indicator_context,
            output: _,
            line_prefix,
            ignore_space_at_eol,
            ignore_cr_at_eol,
            ignore_space_change,
            ignore_all_space,
            ignore_blank_lines,
            ignore_matching_lines,
            text,
            no_ext_diff,
            ext_diff,
            no_textconv,
            textconv,
            color,
            no_color,
            color_moved,
            color_moved_ws,
            no_color_moved,
            no_color_moved_ws,
            indent_heuristic,
            no_indent_heuristic,
            rename_empty,
            no_rename_empty,
            ita_invisible_in_index,
            find_object,
            diff_merges,
            merge_base,
            no_diff_merges,
            remerge_diff,
            combined_all_paths,
            dd,
            ws_error_highlight,
            quiet,
            exit_code,
            treeish,
            paths,
        } => super::diff_commands::diff_index(runtime::PlumbingDiffOptions {
            recursive: false,
            nul_terminated,
            patch,
            patch_with_raw,
            patch_with_stat,
            no_patch,
            binary,
            stat,
            no_stat,
            compact_summary,
            numstat,
            shortstat,
            check,
            dirstat,
            cumulative,
            dirstat_by_file,
            raw,
            summary,
            name_status,
            name_only,
            find_renames,
            break_rewrites,
            irreversible_delete,
            submodule,
            ignore_submodules,
            find_copies,
            find_copies_harder,
            omit_unmerged: false,
            base: false,
            ours: false,
            theirs: false,
            no_renames,
            rename_limit_short,
            merge,
            combined,
            dense_combined,
            tree_in_diff,
            reverse,
            root: false,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            order_file,
            skip_to,
            rotate_to,
            diff_filter,
            word_diff,
            color_words,
            word_diff_regex,
            abbrev: abbrev.last().cloned(),
            no_abbrev,
            abbrev_commit: false,
            no_abbrev_commit: false,
            full_index,
            no_full_index,
            no_prefix,
            default_prefix,
            src_prefix,
            dst_prefix,
            relative,
            no_relative,
            unified,
            encoding: None,
            oneline: false,
            function_context,
            expand_tabs: false,
            no_expand_tabs: false,
            inter_hunk_context,
            minimal,
            patience,
            histogram,
            diff_algorithm,
            anchored,
            output_indicator_new,
            output_indicator_old,
            output_indicator_context,
            line_prefix,
            ignore_space_at_eol,
            ignore_cr_at_eol,
            ignore_space_change,
            ignore_all_space,
            ignore_blank_lines,
            ignore_matching_lines,
            text,
            no_ext_diff,
            ext_diff,
            no_textconv,
            textconv,
            color,
            no_color,
            color_moved,
            color_moved_ws,
            no_color_moved,
            no_color_moved_ws,
            indent_heuristic,
            no_indent_heuristic,
            rename_empty,
            no_rename_empty,
            ita_invisible_in_index,
            merge_base,
            no_diff_merges,
            find_object,
            diff_merges,
            remerge_diff,
            combined_all_paths,
            dd,
            ws_error_highlight,
            no_notes: false,
            quiet,
            exit_code,
            pretty: None,
            notes: false,
            show_notes: false,
            show_notes_by_default: false,
            standard_notes: false,
            no_standard_notes: false,
            show_signature: false,
            no_commit_id: false,
            always: false,
            format: None,
            verbose: false,
            stdin: false,
            treeish: Some(treeish),
            new_treeish: None,
            cached,
            paths,
        }),
        runtime::Command::DiffTree {
            stdin,
            nul_terminated,
            recursive,
            patch,
            patch_with_raw,
            patch_with_stat,
            no_patch,
            binary,
            stat,
            no_stat,
            compact_summary,
            numstat,
            shortstat,
            check,
            dirstat,
            cumulative,
            dirstat_by_file,
            raw,
            summary,
            name_status,
            name_only,
            mut find_renames,
            mut break_rewrites,
            irreversible_delete,
            submodule,
            ignore_submodules,
            mut find_copies,
            find_copies_harder,
            no_renames,
            rename_limit_short,
            merge,
            combined,
            dense_combined,
            tree_in_diff,
            reverse,
            reverse_long: _,
            root,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            order_file,
            skip_to,
            rotate_to,
            diff_filter,
            word_diff,
            color_words,
            word_diff_regex,
            abbrev,
            no_abbrev,
            abbrev_commit,
            no_abbrev_commit,
            full_index,
            no_full_index,
            no_prefix,
            default_prefix,
            src_prefix,
            dst_prefix,
            relative,
            no_relative,
            unified,
            encoding,
            oneline,
            function_context,
            expand_tabs,
            no_expand_tabs,
            inter_hunk_context,
            minimal,
            patience,
            histogram,
            diff_algorithm,
            anchored,
            output_indicator_new,
            output_indicator_old,
            output_indicator_context,
            output: _,
            line_prefix,
            ignore_space_at_eol,
            ignore_cr_at_eol,
            ignore_space_change,
            ignore_all_space,
            ignore_blank_lines,
            ignore_matching_lines,
            text,
            no_ext_diff,
            ext_diff,
            no_textconv,
            textconv,
            color,
            no_color,
            color_moved,
            color_moved_ws,
            no_color_moved,
            no_color_moved_ws,
            indent_heuristic,
            no_indent_heuristic,
            rename_empty,
            no_rename_empty,
            ita_invisible_in_index,
            merge_base,
            no_diff_merges,
            find_object,
            diff_merges,
            remerge_diff,
            combined_all_paths,
            dd,
            ws_error_highlight,
            no_notes,
            quiet,
            exit_code,
            pretty,
            notes,
            show_notes,
            show_notes_by_default,
            standard_notes,
            no_standard_notes,
            show_signature,
            no_commit_id,
            always,
            format,
            verbose,
            mut old,
            mut new,
            paths,
        } => {
            normalize_diff_tree_similarity_operand(&mut find_renames, &mut old, &mut new);
            normalize_diff_tree_similarity_operand(&mut find_copies, &mut old, &mut new);
            normalize_diff_tree_similarity_operand(&mut break_rewrites, &mut old, &mut new);
            let (treeish, paths) = if stdin {
                let mut stdin_paths = Vec::new();
                if let Some(path) = old {
                    stdin_paths.push(PathBuf::from(path));
                }
                stdin_paths.extend(paths);
                (None, stdin_paths)
            } else {
                (old, paths)
            };
            super::diff_commands::diff_tree(runtime::PlumbingDiffOptions {
                recursive,
                nul_terminated,
                patch,
                patch_with_raw,
                patch_with_stat,
                no_patch,
                binary,
                stat,
                no_stat,
                compact_summary,
                numstat,
                shortstat,
                check,
                dirstat,
                cumulative,
                dirstat_by_file,
                raw,
                summary,
                name_status,
                name_only,
                find_renames,
                break_rewrites,
                irreversible_delete,
                submodule,
                ignore_submodules,
                find_copies,
                find_copies_harder,
                omit_unmerged: false,
                base: false,
                ours: false,
                theirs: false,
                no_renames,
                rename_limit_short,
                merge,
                combined,
                dense_combined,
                tree_in_diff,
                reverse,
                root,
                pickaxe_string,
                pickaxe_regex,
                pickaxe_regex_mode,
                pickaxe_all,
                order_file,
                skip_to,
                rotate_to,
                diff_filter,
                word_diff,
                color_words,
                word_diff_regex,
                abbrev: abbrev.last().cloned(),
                no_abbrev,
                abbrev_commit,
                no_abbrev_commit,
                full_index,
                no_full_index,
                no_prefix,
                default_prefix,
                src_prefix,
                dst_prefix,
                relative,
                no_relative,
                unified,
                encoding,
                oneline,
                function_context,
                expand_tabs,
                no_expand_tabs,
                inter_hunk_context,
                minimal,
                patience,
                histogram,
                diff_algorithm,
                anchored,
                output_indicator_new,
                output_indicator_old,
                output_indicator_context,
                line_prefix,
                ignore_space_at_eol,
                ignore_cr_at_eol,
                ignore_space_change,
                ignore_all_space,
                ignore_blank_lines,
                ignore_matching_lines,
                text,
                no_ext_diff,
                ext_diff,
                no_textconv,
                textconv,
                color,
                no_color,
                color_moved,
                color_moved_ws,
                no_color_moved,
                no_color_moved_ws,
                indent_heuristic,
                no_indent_heuristic,
                rename_empty,
                no_rename_empty,
                ita_invisible_in_index,
                merge_base,
                no_diff_merges,
                find_object,
                diff_merges,
                remerge_diff,
                combined_all_paths,
                dd,
                ws_error_highlight,
                no_notes,
                quiet,
                exit_code,
                pretty,
                notes,
                show_notes,
                show_notes_by_default,
                standard_notes,
                no_standard_notes,
                show_signature,
                no_commit_id,
                always,
                format,
                verbose,
                stdin,
                treeish,
                new_treeish: new,
                cached: false,
                paths,
            })
        }
        runtime::Command::DiffPairs {
            nul_terminated,
            patch,
            no_patch,
            stat,
            numstat,
            shortstat,
            raw,
            summary,
            name_status,
            name_only,
            word_diff,
            quiet,
        } => super::diff_commands::diff_pairs(runtime::DiffPairsOptions {
            nul_terminated,
            patch,
            no_patch,
            stat,
            numstat,
            shortstat,
            raw,
            summary,
            name_status,
            name_only,
            word_diff,
            quiet,
        }),
        _ => unreachable!("non-diff command dispatched to diff"),
    }
}

fn normalize_porcelain_unified_operands(
    unified: Option<String>,
    paths: Vec<PathBuf>,
) -> (Option<String>, Vec<PathBuf>) {
    let Some(value) = unified else {
        return (None, paths);
    };
    if value.bytes().all(|byte| byte.is_ascii_digit()) {
        return (Some(value), paths);
    }
    let mut normalized_paths = Vec::with_capacity(paths.len() + 1);
    normalized_paths.push(PathBuf::from(value));
    normalized_paths.extend(paths);
    (Some("3".to_owned()), normalized_paths)
}

fn normalize_diff_tree_similarity_operand(
    option: &mut Option<String>,
    old: &mut Option<String>,
    new: &mut Option<String>,
) {
    let Some(value) = option.as_ref() else {
        return;
    };
    if new.is_some() || old.is_none() || is_similarity_threshold_value(value) {
        return;
    }
    let consumed_old = option.take();
    *new = old.take();
    *old = consumed_old;
    *option = Some(String::new());
}

fn is_similarity_threshold_value(value: &str) -> bool {
    if value.is_empty() {
        return true;
    }
    let digits = value.strip_suffix('%').unwrap_or(value);
    !digits.is_empty() && digits.bytes().all(|byte| byte.is_ascii_digit())
}
