use std::path::PathBuf;

use crate::runtime;

pub(crate) fn dispatch(command: runtime::Command) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Diff {
            no_index,
            recursive: _,
            nul_terminated,
            cached,
            reverse,
            check,
            patch: _,
            patch_with_raw,
            patch_with_stat,
            no_patch,
            binary,
            stat,
            compact_summary,
            numstat,
            shortstat,
            dirstat,
            dirstat_by_file,
            raw,
            summary,
            name_status,
            name_only,
            find_renames,
            break_rewrites,
            irreversible_delete,
            submodule,
            ignore_submodules,
            find_copies,
            find_copies_harder,
            no_renames,
            dense_combined,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            order_file,
            skip_to,
            rotate_to,
            diff_filter,
            word_diff,
            abbrev,
            no_abbrev,
            full_index,
            no_full_index,
            no_prefix,
            default_prefix,
            src_prefix,
            dst_prefix,
            relative,
            no_relative,
            unified,
            inter_hunk_context,
            minimal,
            patience,
            histogram,
            diff_algorithm,
            anchored,
            output_indicator_new,
            output_indicator_old,
            output_indicator_context,
            line_prefix,
            ignore_space_at_eol,
            ignore_cr_at_eol,
            ignore_space_change,
            ignore_all_space,
            ignore_blank_lines,
            ignore_matching_lines,
            no_ext_diff,
            no_textconv,
            text,
            color,
            no_color,
            no_color_moved,
            no_color_moved_ws,
            quiet,
            exit_code,
            paths,
        } => {
            let (unified, paths) = normalize_porcelain_unified_operands(unified, paths);
            super::diff_commands::diff(runtime::DiffOptions {
                no_index,
                nul_terminated,
                cached,
                reverse,
                check,
                patch_with_raw,
                patch_with_stat,
                stat,
                compact_summary,
                no_patch,
                binary,
                numstat,
                shortstat,
                dirstat,
                dirstat_by_file,
                raw,
                summary,
                name_status,
                name_only,
                find_renames,
                break_rewrites,
                irreversible_delete,
                submodule,
                ignore_submodules,
                find_copies,
                find_copies_harder,
                no_renames,
                dense_combined,
                pickaxe_string,
                pickaxe_regex,
                pickaxe_regex_mode,
                pickaxe_all,
                order_file,
                skip_to,
                rotate_to,
                diff_filter,
                word_diff,
                abbrev,
                no_abbrev,
                full_index,
                no_full_index,
                no_prefix,
                default_prefix,
                src_prefix,
                dst_prefix,
                relative,
                no_relative,
                unified,
                inter_hunk_context,
                minimal,
                patience,
                histogram,
                diff_algorithm,
                anchored,
                output_indicator_new,
                output_indicator_old,
                output_indicator_context,
                line_prefix,
                ignore_space_at_eol,
                ignore_cr_at_eol,
                ignore_space_change,
                ignore_all_space,
                ignore_blank_lines,
                ignore_matching_lines,
                no_ext_diff,
                no_textconv,
                text,
                color,
                no_color,
                no_color_moved,
                no_color_moved_ws,
                quiet,
                exit_code,
                paths,
            })
        }
        runtime::Command::Difftool {
            cached,
            tool,
            extcmd,
            no_prompt: _,
            prompt: _,
            paths,
        } => super::diff_commands::difftool(cached, tool.as_deref(), extcmd.as_deref(), paths),
        runtime::Command::DiffFiles {
            nul_terminated,
            patch,
            patch_with_raw,
            patch_with_stat,
            no_patch,
            binary,
            stat,
            compact_summary,
            numstat,
            shortstat,
            raw,
            summary,
            name_status,
            name_only,
            find_renames,
            break_rewrites,
            irreversible_delete,
            submodule,
            ignore_submodules,
            find_copies,
            find_copies_harder,
            merge: false,
            reverse,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            order_file,
            skip_to,
            rotate_to,
            diff_filter,
            word_diff,
            abbrev,
            no_abbrev,
            full_index,
            no_full_index,
            no_prefix,
            default_prefix,
            src_prefix,
            dst_prefix,
            relative,
            no_relative,
            unified,
            inter_hunk_context,
            minimal,
            patience,
            histogram,
            diff_algorithm,
            anchored,
            output_indicator_new,
            output_indicator_old,
            output_indicator_context,
            ignore_space_at_eol,
            ignore_cr_at_eol,
            ignore_space_change,
            ignore_all_space,
            ignore_blank_lines,
            ignore_matching_lines,
            text,
            no_ext_diff,
            no_textconv,
            color,
            no_color,
            no_color_moved,
            no_color_moved_ws,
            quiet,
            exit_code,
            quiet_unmerged: _,
            paths,
        } => super::diff_commands::diff_files(runtime::PlumbingDiffOptions {
            recursive: false,
            nul_terminated,
            patch,
            patch_with_raw,
            patch_with_stat,
            no_patch,
            binary,
            stat,
            compact_summary,
            numstat,
            shortstat,
            raw,
            summary,
            name_status,
            name_only,
            find_renames,
            break_rewrites,
            irreversible_delete,
            submodule,
            ignore_submodules,
            find_copies,
            find_copies_harder,
            merge: false,
            combined: false,
            dense_combined: false,
            reverse,
            root: false,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            order_file,
            skip_to,
            rotate_to,
            diff_filter,
            word_diff,
            abbrev,
            no_abbrev,
            full_index,
            no_full_index,
            no_prefix,
            default_prefix,
            src_prefix,
            dst_prefix,
            relative,
            no_relative,
            unified,
            inter_hunk_context,
            minimal,
            patience,
            histogram,
            diff_algorithm,
            anchored,
            output_indicator_new,
            output_indicator_old,
            output_indicator_context,
            ignore_space_at_eol,
            ignore_cr_at_eol,
            ignore_space_change,
            ignore_all_space,
            ignore_blank_lines,
            ignore_matching_lines,
            text,
            no_ext_diff,
            no_textconv,
            color,
            no_color,
            no_color_moved,
            no_color_moved_ws,
            quiet,
            exit_code,
            pretty: None,
            notes: false,
            format: None,
            stdin: false,
            treeish: None,
            new_treeish: None,
            cached: false,
            paths,
        }),
        runtime::Command::DiffIndex {
            nul_terminated,
            cached,
            patch,
            patch_with_raw,
            patch_with_stat,
            no_patch,
            binary,
            stat,
            compact_summary,
            numstat,
            shortstat,
            raw,
            summary,
            name_status,
            name_only,
            find_renames,
            break_rewrites,
            irreversible_delete,
            submodule,
            ignore_submodules,
            find_copies,
            find_copies_harder,
            merge,
            reverse,
            root: _,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            order_file,
            skip_to,
            rotate_to,
            diff_filter,
            word_diff,
            abbrev,
            no_abbrev,
            full_index,
            no_full_index,
            no_prefix,
            default_prefix,
            src_prefix,
            dst_prefix,
            relative,
            no_relative,
            unified,
            inter_hunk_context,
            minimal,
            patience,
            histogram,
            diff_algorithm,
            anchored,
            output_indicator_new,
            output_indicator_old,
            output_indicator_context,
            ignore_space_at_eol,
            ignore_cr_at_eol,
            ignore_space_change,
            ignore_all_space,
            ignore_blank_lines,
            ignore_matching_lines,
            text,
            no_ext_diff,
            no_textconv,
            color,
            no_color,
            no_color_moved,
            no_color_moved_ws,
            quiet,
            exit_code,
            treeish,
            paths,
        } => super::diff_commands::diff_index(runtime::PlumbingDiffOptions {
            recursive: false,
            nul_terminated,
            patch,
            patch_with_raw,
            patch_with_stat,
            no_patch,
            binary,
            stat,
            compact_summary,
            numstat,
            shortstat,
            raw,
            summary,
            name_status,
            name_only,
            find_renames,
            break_rewrites,
            irreversible_delete,
            submodule,
            ignore_submodules,
            find_copies,
            find_copies_harder,
            merge,
            combined: false,
            dense_combined: false,
            reverse,
            root: false,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            order_file,
            skip_to,
            rotate_to,
            diff_filter,
            word_diff,
            abbrev,
            no_abbrev,
            full_index,
            no_full_index,
            no_prefix,
            default_prefix,
            src_prefix,
            dst_prefix,
            relative,
            no_relative,
            unified,
            inter_hunk_context,
            minimal,
            patience,
            histogram,
            diff_algorithm,
            anchored,
            output_indicator_new,
            output_indicator_old,
            output_indicator_context,
            ignore_space_at_eol,
            ignore_cr_at_eol,
            ignore_space_change,
            ignore_all_space,
            ignore_blank_lines,
            ignore_matching_lines,
            text,
            no_ext_diff,
            no_textconv,
            color,
            no_color,
            no_color_moved,
            no_color_moved_ws,
            quiet,
            exit_code,
            pretty: None,
            notes: false,
            format: None,
            stdin: false,
            treeish: Some(treeish),
            new_treeish: None,
            cached,
            paths,
        }),
        runtime::Command::DiffTree {
            stdin,
            nul_terminated,
            recursive,
            patch,
            patch_with_raw,
            patch_with_stat,
            no_patch,
            binary,
            stat,
            compact_summary,
            numstat,
            shortstat,
            raw,
            summary,
            name_status,
            name_only,
            find_renames,
            break_rewrites,
            irreversible_delete,
            submodule,
            ignore_submodules,
            find_copies,
            find_copies_harder,
            merge,
            combined,
            dense_combined,
            reverse,
            root,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            order_file,
            skip_to,
            rotate_to,
            diff_filter,
            word_diff,
            abbrev,
            no_abbrev,
            full_index,
            no_full_index,
            no_prefix,
            default_prefix,
            src_prefix,
            dst_prefix,
            relative,
            no_relative,
            unified,
            inter_hunk_context,
            minimal,
            patience,
            histogram,
            diff_algorithm,
            anchored,
            output_indicator_new,
            output_indicator_old,
            output_indicator_context,
            ignore_space_at_eol,
            ignore_cr_at_eol,
            ignore_space_change,
            ignore_all_space,
            ignore_blank_lines,
            ignore_matching_lines,
            text,
            no_ext_diff,
            no_textconv,
            color,
            no_color,
            no_color_moved,
            no_color_moved_ws,
            quiet,
            exit_code,
            pretty,
            notes,
            format,
            old,
            new,
            paths,
        } => {
            let (treeish, paths) = if stdin {
                let mut stdin_paths = Vec::new();
                if let Some(path) = old {
                    stdin_paths.push(PathBuf::from(path));
                }
                stdin_paths.extend(paths);
                (None, stdin_paths)
            } else {
                (old, paths)
            };
            super::diff_commands::diff_tree(runtime::PlumbingDiffOptions {
                recursive,
                nul_terminated,
                patch,
                patch_with_raw,
                patch_with_stat,
                no_patch,
                binary,
                stat,
                compact_summary,
                numstat,
                shortstat,
                raw,
                summary,
                name_status,
                name_only,
                find_renames,
                break_rewrites,
                irreversible_delete,
                submodule,
                ignore_submodules,
                find_copies,
                find_copies_harder,
                merge,
                combined,
                dense_combined,
                reverse,
                root,
                pickaxe_string,
                pickaxe_regex,
                pickaxe_regex_mode,
                pickaxe_all,
                order_file,
                skip_to,
                rotate_to,
                diff_filter,
                word_diff,
                abbrev,
                no_abbrev,
                full_index,
                no_full_index,
                no_prefix,
                default_prefix,
                src_prefix,
                dst_prefix,
                relative,
                no_relative,
                unified,
                inter_hunk_context,
                minimal,
                patience,
                histogram,
                diff_algorithm,
                anchored,
                output_indicator_new,
                output_indicator_old,
                output_indicator_context,
                ignore_space_at_eol,
                ignore_cr_at_eol,
                ignore_space_change,
                ignore_all_space,
                ignore_blank_lines,
                ignore_matching_lines,
                text,
                no_ext_diff,
                no_textconv,
                color,
                no_color,
                no_color_moved,
                no_color_moved_ws,
                quiet,
                exit_code,
                pretty,
                notes,
                format,
                stdin,
                treeish,
                new_treeish: new,
                cached: false,
                paths,
            })
        }
        runtime::Command::DiffPairs {
            nul_terminated,
            patch,
            no_patch,
            stat,
            numstat,
            shortstat,
            raw,
            summary,
            name_status,
            name_only,
            word_diff,
            quiet,
        } => super::diff_commands::diff_pairs(runtime::DiffPairsOptions {
            nul_terminated,
            patch,
            no_patch,
            stat,
            numstat,
            shortstat,
            raw,
            summary,
            name_status,
            name_only,
            word_diff,
            quiet,
        }),
        _ => unreachable!("non-diff command dispatched to diff"),
    }
}

fn normalize_porcelain_unified_operands(
    unified: Option<String>,
    paths: Vec<PathBuf>,
) -> (Option<String>, Vec<PathBuf>) {
    let Some(value) = unified else {
        return (None, paths);
    };
    if value.bytes().all(|byte| byte.is_ascii_digit()) {
        return (Some(value), paths);
    }
    let mut normalized_paths = Vec::with_capacity(paths.len() + 1);
    normalized_paths.push(PathBuf::from(value));
    normalized_paths.extend(paths);
    (Some("3".to_owned()), normalized_paths)
}
