use crate::runtime;

pub(crate) fn dispatch(command: runtime::Command) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Grep {
            cached,
            quiet,
            ignore_case,
            invert_match,
            line_number,
            files_with_matches,
            name_only,
            files_without_match,
            count,
            max_count,
            with_filename,
            null_terminated,
            full_name,
            heading,
            break_,
            basic_regexp,
            extended_regexp,
            fixed_strings,
            text,
            no_textconv,
            column,
            only_matching,
            pattern,
            args,
        } => super::grep_commands::grep(
            cached,
            quiet,
            ignore_case,
            invert_match,
            line_number,
            files_with_matches,
            name_only,
            files_without_match,
            count,
            max_count,
            with_filename,
            null_terminated,
            full_name,
            heading,
            break_,
            basic_regexp,
            extended_regexp,
            fixed_strings,
            text,
            no_textconv,
            column,
            only_matching,
            &pattern,
            args,
        ),
        _ => unreachable!("non-grep command dispatched to grep"),
    }
}
