use crate::runtime;

pub(crate) struct ReplayOptions {
    pub(crate) all: bool,
    pub(crate) branches: bool,
    pub(crate) tags: bool,
    pub(crate) remotes: bool,
    pub(crate) not: bool,
    pub(crate) stdin: bool,
    pub(crate) count: bool,
    pub(crate) exclude: Vec<String>,
    pub(crate) topo_order: bool,
    pub(crate) date_order: bool,
    pub(crate) author_date_order: bool,
    pub(crate) reverse: bool,
    pub(crate) abbrev_commit: bool,
    pub(crate) no_abbrev_commit: bool,
    pub(crate) author: Option<String>,
    pub(crate) committer: Option<String>,
    pub(crate) encoding: Option<String>,
    pub(crate) alternate_refs: bool,
    pub(crate) glob: Option<String>,
    pub(crate) ignore_missing: bool,
    pub(crate) indexed_objects: bool,
    pub(crate) remove_empty: bool,
    pub(crate) single_worktree: bool,
    pub(crate) unpacked: bool,
    pub(crate) bisect_all: bool,
    pub(crate) bisect_vars: bool,
    pub(crate) boundary: bool,
    pub(crate) first_parent: bool,
    pub(crate) right_only: bool,
    pub(crate) left_only: bool,
    pub(crate) left_right: bool,
    pub(crate) cherry: bool,
    pub(crate) cherry_pick: bool,
    pub(crate) cherry_mark: bool,
    pub(crate) parents: bool,
    pub(crate) objects: bool,
    pub(crate) objects_edge: bool,
    pub(crate) objects_edge_aggressive: bool,
    pub(crate) show_signature: bool,
    pub(crate) walk_reflogs: bool,
    pub(crate) no_walk: bool,
    pub(crate) do_walk: bool,
    pub(crate) no_merges: bool,
    pub(crate) merge: bool,
    pub(crate) dense: bool,
    pub(crate) sparse: bool,
    pub(crate) full_history: bool,
    pub(crate) children: bool,
    pub(crate) ancestry_path: bool,
    pub(crate) simplify_merges: bool,
    pub(crate) simplify_by_decoration: bool,
    pub(crate) in_commit_order: bool,
    pub(crate) commit_header: bool,
    pub(crate) no_commit_header: bool,
    pub(crate) disk_usage: bool,
    pub(crate) expand_tabs: bool,
    pub(crate) no_expand_tabs: bool,
    pub(crate) show_linear_break: Option<String>,
    pub(crate) header: bool,
    pub(crate) notes: bool,
    pub(crate) no_notes: bool,
    pub(crate) show_notes: bool,
    pub(crate) show_notes_by_default: bool,
    pub(crate) standard_notes: bool,
    pub(crate) no_standard_notes: bool,
    pub(crate) reflog: bool,
    pub(crate) bisect: bool,
    pub(crate) grep_reflog: Vec<String>,
    pub(crate) grep: Vec<String>,
    pub(crate) invert_grep: bool,
    pub(crate) all_match: bool,
    pub(crate) regexp_ignore_case: bool,
    pub(crate) basic_regexp: bool,
    pub(crate) extended_regexp: bool,
    pub(crate) fixed_strings: bool,
    pub(crate) perl_regexp: bool,
    pub(crate) pretty: Option<String>,
    pub(crate) oneline: bool,
    pub(crate) format: Option<String>,
    pub(crate) date: Option<String>,
    pub(crate) relative_date: bool,
    pub(crate) graph: bool,
    pub(crate) object_names: bool,
    pub(crate) no_object_names: bool,
    pub(crate) exclude_promisor_objects: bool,
    pub(crate) filter: Option<String>,
    pub(crate) filter_print_omitted: bool,
    pub(crate) filter_provided_objects: bool,
    pub(crate) progress: Option<String>,
    pub(crate) missing: Option<String>,
    pub(crate) use_bitmap_index: bool,
    pub(crate) quiet: bool,
    pub(crate) show_pulls: bool,
    pub(crate) timestamp: bool,
    pub(crate) no_filter: bool,
    pub(crate) max_count: Option<String>,
    pub(crate) max_age: Option<String>,
    pub(crate) min_age: Option<String>,
    pub(crate) skip: Option<usize>,
    pub(crate) since: Option<String>,
    pub(crate) since_as_filter: Option<String>,
    pub(crate) until: Option<String>,
    pub(crate) max_parents: Option<String>,
    pub(crate) no_max_parents: bool,
    pub(crate) min_parents: Option<String>,
    pub(crate) no_min_parents: bool,
    pub(crate) exclude_first_parent_only: bool,
    pub(crate) merges: bool,
    pub(crate) exclude_hidden: Option<String>,
    pub(crate) contained: bool,
    pub(crate) advance: Option<String>,
    pub(crate) onto: Option<String>,
    pub(crate) revision_ranges: Vec<String>,
}

pub(crate) fn dispatch(
    command: runtime::Command,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Replay {
            all,
            branches,
            tags,
            remotes,
            not,
            stdin,
            count,
            exclude,
            topo_order,
            date_order,
            author_date_order,
            reverse,
            abbrev_commit,
            no_abbrev_commit,
            author,
            committer,
            encoding,
            alternate_refs,
            glob,
            ignore_missing,
            indexed_objects,
            remove_empty,
            single_worktree,
            unpacked,
            bisect_all,
            bisect_vars,
            boundary,
            first_parent,
            right_only,
            left_only,
            left_right,
            cherry,
            cherry_pick,
            cherry_mark,
            parents,
            objects,
            objects_edge,
            objects_edge_aggressive,
            show_signature,
            walk_reflogs,
            no_walk,
            do_walk,
            no_merges,
            merge,
            dense,
            sparse,
            full_history,
            children,
            ancestry_path,
            simplify_merges,
            simplify_by_decoration,
            in_commit_order,
            commit_header,
            no_commit_header,
            disk_usage,
            expand_tabs,
            no_expand_tabs,
            show_linear_break,
            header,
            notes,
            no_notes,
            show_notes,
            show_notes_by_default,
            standard_notes,
            no_standard_notes,
            reflog,
            bisect,
            grep_reflog,
            grep,
            invert_grep,
            all_match,
            regexp_ignore_case,
            basic_regexp,
            extended_regexp,
            fixed_strings,
            perl_regexp,
            pretty,
            oneline,
            format,
            date,
            relative_date,
            graph,
            object_names,
            no_object_names,
            exclude_promisor_objects,
            filter,
            filter_print_omitted,
            filter_provided_objects,
            progress,
            missing,
            use_bitmap_index,
            quiet,
            show_pulls,
            timestamp,
            no_filter,
            max_count,
            max_age,
            min_age,
            skip,
            since,
            since_as_filter,
            until,
            max_parents,
            no_max_parents,
            min_parents,
            no_min_parents,
            exclude_first_parent_only,
            merges,
            exclude_hidden,
            contained,
            advance,
            onto,
            revision_ranges,
        } => run_replay(ReplayOptions {
            all,
            branches,
            tags,
            remotes,
            not: not > 0,
            stdin,
            count,
            exclude,
            topo_order,
            date_order,
            author_date_order,
            reverse,
            abbrev_commit,
            no_abbrev_commit,
            author,
            committer,
            encoding,
            alternate_refs,
            glob,
            ignore_missing,
            indexed_objects,
            remove_empty,
            single_worktree,
            unpacked,
            bisect_all,
            bisect_vars,
            boundary,
            first_parent,
            right_only,
            left_only,
            left_right,
            cherry,
            cherry_pick,
            cherry_mark,
            parents,
            objects,
            objects_edge,
            objects_edge_aggressive,
            show_signature,
            walk_reflogs,
            no_walk,
            do_walk,
            no_merges,
            merge,
            dense,
            sparse,
            full_history,
            children,
            ancestry_path,
            simplify_merges,
            simplify_by_decoration,
            in_commit_order,
            commit_header,
            no_commit_header,
            disk_usage,
            expand_tabs,
            no_expand_tabs,
            show_linear_break,
            header,
            notes,
            no_notes,
            show_notes,
            show_notes_by_default,
            standard_notes,
            no_standard_notes,
            reflog,
            bisect,
            grep_reflog,
            grep,
            invert_grep,
            all_match,
            regexp_ignore_case,
            basic_regexp,
            extended_regexp,
            fixed_strings,
            perl_regexp,
            pretty,
            oneline,
            format,
            date,
            relative_date,
            graph,
            object_names,
            no_object_names,
            exclude_promisor_objects,
            filter,
            filter_print_omitted,
            filter_provided_objects,
            progress,
            missing,
            use_bitmap_index,
            quiet,
            show_pulls,
            timestamp,
            no_filter,
            max_count,
            max_age,
            min_age,
            skip,
            since,
            since_as_filter,
            until,
            max_parents,
            no_max_parents,
            min_parents,
            no_min_parents,
            exclude_first_parent_only,
            merges,
            exclude_hidden,
            contained,
            advance,
            onto,
            revision_ranges,
        }),
        runtime::Command::History { command } => run_history(command, raw_args),
        runtime::Command::RangeDiff {
            no_dual_color,
            no_no_dual_color,
            creation_factor,
            left_only,
            right_only,
            notes,
            no_notes,
            ranges,
        } => run_range_diff(
            no_dual_color > 0,
            no_no_dual_color,
            creation_factor,
            left_only,
            right_only,
            notes,
            no_notes,
            ranges,
        ),
        runtime::Command::FilterBranch {
            force,
            prune_empty,
            msg_filter,
            tree_filter,
            index_filter,
            env_filter,
            parent_filter,
            commit_filter,
            tag_name_filter,
            subdirectory_filter,
            original,
            temp_dir,
            setup,
            state_branch,
            revs,
        } => super::history_commands::filter_branch(super::history_commands::FilterBranchOptions {
            force,
            prune_empty,
            msg_filter,
            tree_filter,
            index_filter,
            env_filter,
            parent_filter,
            commit_filter,
            tag_name_filter,
            subdirectory_filter,
            original,
            temp_dir,
            setup,
            state_branch,
            revs,
        }),
        runtime::Command::Shortlog {
            oneline,
            all,
            exclude,
            exclude_first_parent_only,
            exclude_hidden,
            exclude_promisor_objects,
            branches,
            tags,
            author,
            pretty,
            encoding,
            abbrev_commit,
            committer,
            numbered,
            summary,
            email,
            no_merges,
            merges,
            merge,
            do_walk,
            no_walk,
            topo_order,
            date_order,
            author_date_order,
            ancestry_path,
            reverse,
            alternate_refs,
            bisect,
            bisect_all,
            bisect_vars,
            cherry,
            count,
            dense,
            full_history,
            glob,
            in_commit_order,
            expand_tabs,
            show_linear_break,
            left_right,
            left_only,
            right_only,
            cherry_pick,
            cherry_mark,
            boundary,
            children,
            max_parents,
            no_max_parents,
            min_parents,
            no_min_parents,
            first_parent,
            ignore_missing,
            indexed_objects,
            unpacked,
            remotes,
            remove_empty,
            notes,
            no_notes,
            show_notes,
            show_notes_by_default,
            standard_notes,
            no_standard_notes,
            no_abbrev_commit,
            no_expand_tabs,
            objects_edge,
            objects_edge_aggressive,
            quiet,
            show_pulls,
            simplify_merges,
            simplify_by_decoration,
            sparse,
            parents,
            objects,
            graph,
            show_signature,
            format,
            date,
            relative_date,
            group,
            wrap,
            stdin,
            reflog,
            walk_reflogs,
            grep_reflog,
            grep,
            invert_grep,
            all_match,
            regexp_ignore_case,
            basic_regexp,
            extended_regexp,
            fixed_strings,
            perl_regexp,
            object_names,
            no_object_names,
            mailmap,
            source,
            commit_header,
            disk_usage,
            single_worktree,
            filter,
            filter_print_omitted,
            filter_provided_objects,
            header,
            progress,
            no_filter,
            missing,
            use_bitmap_index,
            timestamp,
            max_count,
            max_age,
            skip,
            min_age,
            since,
            since_as_filter,
            until,
            revs,
        } => super::history_commands::shortlog(super::history_commands::ShortlogOptions {
            oneline,
            all,
            exclude,
            exclude_first_parent_only,
            exclude_hidden: exclude_hidden.as_deref(),
            exclude_promisor_objects,
            author: author.as_deref(),
            pretty: pretty.as_deref(),
            encoding: encoding.as_deref(),
            abbrev_commit,
            max_count: max_count.as_deref(),
            max_age: max_age.as_deref(),
            skip,
            min_age: min_age.as_deref(),
            since: since.as_deref(),
            since_as_filter: since_as_filter.as_deref(),
            until: until.as_deref(),
            committer,
            numbered,
            summary,
            email,
            no_merges,
            merges,
            merge,
            do_walk,
            no_walk,
            topo_order,
            date_order,
            author_date_order,
            ancestry_path,
            reverse,
            alternate_refs,
            bisect,
            bisect_all,
            bisect_vars,
            cherry,
            count,
            dense,
            full_history,
            glob: glob.as_deref(),
            in_commit_order,
            expand_tabs,
            show_linear_break,
            left_right,
            left_only,
            right_only,
            cherry_pick,
            cherry_mark,
            boundary,
            children,
            max_parents: max_parents.as_deref(),
            no_max_parents,
            min_parents: min_parents.as_deref(),
            no_min_parents,
            first_parent,
            ignore_missing,
            indexed_objects,
            unpacked,
            remotes,
            remove_empty,
            notes,
            no_notes,
            show_notes,
            show_notes_by_default,
            standard_notes,
            no_standard_notes,
            no_abbrev_commit,
            no_expand_tabs,
            objects_edge,
            objects_edge_aggressive,
            quiet,
            show_pulls,
            simplify_merges,
            simplify_by_decoration,
            sparse,
            parents,
            objects,
            graph,
            show_signature,
            format: format.last().map(String::as_str),
            date: date.last().map(String::as_str),
            relative_date,
            group,
            wrap: wrap.last().map(String::as_str),
            stdin,
            reflog,
            walk_reflogs,
            grep_reflog,
            grep,
            invert_grep,
            all_match,
            regexp_ignore_case,
            basic_regexp,
            extended_regexp,
            fixed_strings,
            perl_regexp,
            object_names,
            no_object_names,
            mailmap,
            source,
            commit_header,
            disk_usage,
            single_worktree,
            filter: filter.as_deref(),
            filter_print_omitted,
            filter_provided_objects,
            header,
            progress,
            no_filter,
            missing,
            use_bitmap_index,
            timestamp,
            raw_args,
            revs: extend_history_ref_selector_revs(revs, branches, tags, Vec::new()),
        }),
        runtime::Command::Blame {
            help,
            long,
            root,
            contents,
            encoding,
            first_parent,
            ignore_rev,
            ignore_revs_file,
            reverse,
            revs_file,
            args,
        } => super::history_commands::blame(
            long,
            root,
            false,
            serialize_blame_args(
                help,
                contents,
                encoding,
                first_parent,
                ignore_rev,
                ignore_revs_file,
                reverse,
                revs_file,
                args,
            ),
        ),
        runtime::Command::Annotate {
            help,
            long,
            porcelain,
            incremental,
            line_porcelain,
            contents,
            date,
            encoding,
            first_parent,
            ignore_rev,
            ignore_revs_file,
            progress,
            no_progress,
            color_lines,
            color_by_age,
            reverse,
            root,
            show_stats,
            copies,
            line_ranges,
            moves,
            revs_file,
            blank_boundary,
            raw_timestamp,
            args,
        } => super::history_commands::blame(
            long,
            true,
            true,
            serialize_annotate_args(
                help,
                porcelain,
                incremental,
                line_porcelain,
                contents,
                date,
                encoding,
                first_parent,
                ignore_rev,
                ignore_revs_file,
                progress,
                no_progress,
                color_lines,
                color_by_age,
                reverse,
                root,
                show_stats,
                copies,
                line_ranges,
                moves,
                revs_file,
                blank_boundary,
                raw_timestamp,
                args,
            ),
        ),
        runtime::Command::ShowBranch {
            all,
            remotes,
            current,
            topo_order,
            date_order,
            sparse,
            color,
            no_color,
            more,
            list,
            independent,
            merge_base,
            sha1_name,
            no_name,
            topics,
            reflog,
            revs,
        } => super::history_commands::show_branch(super::history_commands::ShowBranchOptions {
            all,
            remotes,
            current,
            topo_order,
            date_order,
            sparse,
            color,
            no_color,
            more,
            list,
            independent,
            merge_base,
            sha1_name,
            no_name,
            topics,
            reflog,
            revs,
        }),
        runtime::Command::Cherry {
            verbose,
            no_verbose,
            abbrev,
            upstream,
            head,
            limit,
        } => super::history_commands::cherry(
            verbose > 0 && !no_verbose,
            abbrev,
            upstream.as_deref(),
            head.as_deref(),
            limit.as_deref(),
        ),
        runtime::Command::RequestPull {
            patch,
            start,
            url,
            end,
        } => super::history_commands::request_pull(patch > 0, &start, &url, end.as_deref()),
        runtime::Command::Describe {
            all,
            tags,
            contains,
            long,
            abbrev,
            exact_match,
            always,
            dirty,
            broken,
            candidates,
            debug,
            first_parent,
            matches,
            excludes,
            commits,
        } => super::history_commands::describe(super::history_commands::DescribeOptions {
            all,
            tags,
            contains,
            long,
            abbrev,
            exact_match,
            always,
            dirty,
            broken,
            candidates,
            debug,
            first_parent,
            matches,
            excludes,
            commits,
        }),
        runtime::Command::NameRev {
            name_only,
            tags,
            refs,
            excludes,
            all,
            annotate_stdin,
            undefined: _undefined,
            no_undefined,
            always,
            commits,
        } => super::history_commands::name_rev(super::history_commands::NameRevOptions {
            name_only,
            tags,
            refs,
            excludes,
            all,
            annotate_stdin,
            no_undefined,
            always,
            commits,
        }),
        runtime::Command::Reflog { command, args } => {
            super::history_commands::reflog(serialize_reflog_args(command, args))
        }
        runtime::Command::Log {
            oneline,
            zero,
            all,
            exclude,
            exclude_first_parent_only,
            exclude_hidden,
            exclude_promisor_objects,
            tags,
            author,
            committer,
            alternate_refs,
            bisect,
            bisect_all,
            bisect_vars,
            cherry,
            count,
            glob,
            skip,
            max_parents,
            no_max_parents,
            merges,
            merge,
            max_age,
            min_parents,
            min_age,
            no_min_parents,
            no_merges,
            parents,
            first_parent,
            follow,
            no_diff_merges,
            diff_merges,
            separate_merges,
            dd,
            reverse,
            full_history,
            ancestry_path,
            in_commit_order,
            dense,
            sparse,
            show_pulls,
            show_linear_break,
            simplify_merges,
            simplify_by_decoration,
            topo_order,
            date_order,
            author_date_order,
            left_right,
            left_only,
            right_only,
            cherry_pick,
            cherry_mark,
            boundary,
            children,
            root,
            patch,
            patch_with_stat,
            combined,
            dense_combined,
            stat,
            numstat,
            shortstat,
            raw,
            summary,
            name_only,
            name_status,
            encoding,
            expand_tabs,
            no_expand_tabs,
            notes,
            no_notes,
            show_notes,
            show_notes_by_default,
            standard_notes,
            no_standard_notes,
            decorate,
            decorate_refs,
            decorate_refs_exclude,
            no_decorate,
            clear_decorations,
            abbrev_commit,
            no_abbrev_commit,
            graph,
            objects,
            objects_edge,
            objects_edge_aggressive,
            no_object_names,
            indexed_objects,
            unpacked,
            remove_empty,
            ignore_missing,
            filter,
            full_diff,
            filter_print_omitted,
            filter_provided_objects,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            ignore_matching_lines,
            walk_reflogs,
            reflog,
            do_walk,
            no_walk,
            stdin,
            grep_reflog,
            grep,
            invert_grep,
            all_match,
            regexp_ignore_case,
            basic_regexp,
            extended_regexp,
            fixed_strings,
            perl_regexp,
            format,
            show_signature,
            log_size,
            line_ranges,
            mailmap,
            no_mailmap,
            use_mailmap,
            no_use_mailmap,
            source,
            max_count,
            since,
            since_as_filter,
            until,
            date,
            relative_date,
            pretty,
            single_worktree,
            commit_header,
            no_commit_header,
            disk_usage,
            header,
            progress,
            no_filter,
            missing,
            use_bitmap_index,
            quiet,
            revs,
        } => super::history_commands::log(super::history_commands::LogOptions {
            oneline,
            zero,
            all,
            exclude,
            exclude_first_parent_only,
            exclude_hidden: exclude_hidden.as_deref(),
            exclude_promisor_objects,
            author: author.as_deref(),
            committer: committer.as_deref(),
            alternate_refs,
            bisect,
            bisect_all,
            bisect_vars,
            cherry,
            count,
            glob: glob.as_deref(),
            skip,
            max_parents: max_parents.as_deref(),
            no_max_parents,
            merges,
            merge,
            max_age: max_age.as_deref(),
            min_parents: min_parents.as_deref(),
            min_age: min_age.as_deref(),
            no_min_parents,
            no_merges,
            parents,
            first_parent,
            follow,
            no_diff_merges,
            diff_merges: diff_merges.as_deref(),
            separate_merges,
            dd,
            reverse,
            full_history,
            ancestry_path,
            in_commit_order,
            dense,
            sparse,
            show_pulls,
            show_linear_break,
            simplify_merges,
            simplify_by_decoration,
            topo_order,
            date_order,
            author_date_order,
            left_right,
            left_only,
            right_only,
            cherry_pick,
            cherry_mark,
            boundary,
            root,
            patch,
            patch_with_stat,
            combined,
            dense_combined,
            stat,
            numstat,
            shortstat,
            raw,
            summary,
            name_only,
            name_status,
            encoding: encoding.as_deref(),
            expand_tabs,
            no_expand_tabs,
            notes,
            no_notes,
            show_notes,
            show_notes_by_default,
            standard_notes,
            no_standard_notes,
            diff_required: false,
            decorate: decorate.as_deref(),
            decorate_refs: decorate_refs.as_deref(),
            decorate_refs_exclude: decorate_refs_exclude.as_deref(),
            no_decorate,
            clear_decorations,
            abbrev_commit,
            no_abbrev_commit,
            graph,
            objects_edge,
            objects_edge_aggressive,
            indexed_objects,
            unpacked,
            remove_empty,
            ignore_missing,
            pickaxe_string: pickaxe_string.as_deref(),
            pickaxe_regex: pickaxe_regex.as_deref(),
            pickaxe_regex_mode,
            pickaxe_all,
            stdin,
            ignore_matching_lines,
            walk_reflogs,
            reflog,
            do_walk,
            no_walk,
            grep_reflog,
            grep,
            invert_grep,
            all_match,
            regexp_ignore_case,
            basic_regexp,
            extended_regexp,
            fixed_strings,
            perl_regexp,
            format: format.as_deref(),
            show_signature,
            log_size,
            line_ranges,
            mailmap,
            no_mailmap,
            use_mailmap,
            no_use_mailmap,
            source,
            max_count: max_count.as_deref(),
            since: since.as_deref(),
            since_as_filter: since_as_filter.as_deref(),
            until: until.as_deref(),
            date: date.as_deref(),
            relative_date,
            pretty: pretty.as_deref(),
            single_worktree,
            commit_header,
            no_commit_header,
            disk_usage,
            header,
            progress,
            no_filter,
            missing,
            use_bitmap_index,
            quiet,
            children,
            objects,
            no_object_names,
            filter,
            full_diff,
            filter_print_omitted,
            filter_provided_objects,
            raw_args,
            revs: extend_history_ref_selector_revs(revs, Vec::new(), tags, Vec::new()),
        }),
        runtime::Command::Whatchanged {
            oneline,
            all,
            parents,
            reverse,
            patch,
            patch_with_stat,
            root,
            combined,
            dense_combined,
            stat,
            numstat,
            shortstat,
            raw,
            summary,
            name_only,
            name_status,
            pickaxe_string,
            pickaxe_regex,
            pickaxe_regex_mode,
            pickaxe_all,
            format,
            max_count,
            since,
            date,
            pretty,
            i_still_use_this: _,
            revs,
        } => super::history_commands::log(super::history_commands::LogOptions {
            oneline,
            zero: false,
            all,
            exclude: Vec::new(),
            exclude_first_parent_only: false,
            exclude_hidden: None,
            exclude_promisor_objects: false,
            author: None,
            committer: None,
            alternate_refs: false,
            bisect: false,
            bisect_all: false,
            bisect_vars: false,
            cherry: false,
            count: false,
            glob: None,
            skip: None,
            max_parents: None,
            no_max_parents: false,
            merges: false,
            merge: false,
            max_age: None,
            min_parents: None,
            min_age: None,
            no_min_parents: false,
            no_merges: false,
            parents,
            first_parent: false,
            no_diff_merges: false,
            diff_merges: None,
            separate_merges: false,
            dd: false,
            reverse,
            full_history: false,
            ancestry_path: false,
            in_commit_order: false,
            dense: false,
            sparse: false,
            show_pulls: false,
            show_linear_break: false,
            simplify_merges: false,
            simplify_by_decoration: false,
            topo_order: false,
            date_order: false,
            author_date_order: false,
            left_right: false,
            left_only: false,
            right_only: false,
            cherry_pick: false,
            cherry_mark: false,
            boundary: false,
            children: false,
            root,
            patch: patch || combined || dense_combined,
            patch_with_stat,
            combined,
            dense_combined,
            stat,
            numstat,
            shortstat,
            raw: raw
                || !(patch
                    || patch_with_stat
                    || combined
                    || dense_combined
                    || stat
                    || numstat
                    || shortstat
                    || summary
                    || name_only
                    || name_status),
            summary,
            name_only,
            name_status,
            encoding: None,
            expand_tabs: false,
            no_expand_tabs: false,
            follow: false,
            notes: false,
            no_notes: false,
            show_notes: false,
            show_notes_by_default: false,
            standard_notes: false,
            no_standard_notes: false,
            diff_required: true,
            graph: false,
            pickaxe_string: pickaxe_string.as_deref(),
            pickaxe_regex: pickaxe_regex.as_deref(),
            pickaxe_regex_mode,
            pickaxe_all,
            objects: false,
            no_object_names: false,
            indexed_objects: false,
            unpacked: false,
            remove_empty: false,
            ignore_missing: false,
            filter: None,
            full_diff: false,
            filter_print_omitted: false,
            filter_provided_objects: false,
            decorate: None,
            decorate_refs: None,
            decorate_refs_exclude: None,
            no_decorate: false,
            clear_decorations: false,
            objects_edge: false,
            objects_edge_aggressive: false,
            stdin: false,
            ignore_matching_lines: Vec::new(),
            walk_reflogs: false,
            reflog: false,
            do_walk: false,
            no_walk: false,
            grep_reflog: Vec::new(),
            grep: Vec::new(),
            invert_grep: false,
            all_match: false,
            regexp_ignore_case: false,
            basic_regexp: false,
            extended_regexp: false,
            fixed_strings: false,
            perl_regexp: false,
            format: format.as_deref(),
            show_signature: false,
            log_size: false,
            line_ranges: Vec::new(),
            mailmap: false,
            no_mailmap: false,
            use_mailmap: false,
            no_use_mailmap: false,
            source: false,
            max_count: max_count.as_deref(),
            since: since.as_deref(),
            since_as_filter: None,
            until: None,
            date: date.as_deref(),
            relative_date: false,
            pretty: pretty.as_deref(),
            abbrev_commit: false,
            no_abbrev_commit: false,
            single_worktree: false,
            commit_header: false,
            no_commit_header: false,
            disk_usage: false,
            header: false,
            progress: false,
            no_filter: false,
            missing: false,
            use_bitmap_index: false,
            quiet: false,
            raw_args,
            revs,
        }),
        runtime::Command::Show {
            no_patch,
            oneline,
            zero,
            stat,
            patch_with_raw,
            patch_with_stat,
            numstat,
            shortstat,
            raw,
            summary,
            name_only,
            name_status,
            encoding,
            expand_tabs,
            no_expand_tabs,
            notes,
            no_notes,
            show_notes,
            show_notes_by_default,
            standard_notes,
            no_standard_notes,
            show_signature,
            abbrev_commit,
            no_abbrev_commit,
            root,
            combined,
            separate_merges,
            first_parent,
            format,
            pretty,
            args,
        } => super::history_commands::show(super::history_commands::ShowOptions {
            no_patch,
            oneline,
            zero,
            stat,
            patch_with_raw,
            patch_with_stat,
            numstat,
            shortstat,
            raw,
            summary,
            name_only,
            name_status,
            encoding: encoding.as_deref(),
            expand_tabs,
            no_expand_tabs,
            notes,
            no_notes,
            show_notes,
            show_notes_by_default,
            standard_notes,
            no_standard_notes,
            show_signature,
            abbrev_commit,
            no_abbrev_commit,
            root,
            combined,
            separate_merges,
            first_parent,
            format: format.as_deref(),
            pretty: pretty.as_deref(),
            args,
        }),
        runtime::Command::RevList {
            oneline,
            header,
            graph,
            all,
            exclude,
            exclude_first_parent_only,
            exclude_hidden,
            exclude_promisor_objects,
            author,
            committer,
            alternate_refs,
            encoding,
            expand_tabs,
            no_expand_tabs,
            notes,
            no_notes,
            show_notes,
            show_notes_by_default,
            standard_notes,
            no_standard_notes,
            abbrev_commit,
            no_abbrev_commit,
            grep,
            invert_grep,
            all_match,
            regexp_ignore_case,
            basic_regexp,
            extended_regexp,
            fixed_strings,
            perl_regexp,
            bisect,
            bisect_all,
            bisect_vars,
            cherry,
            count,
            glob,
            skip,
            branches,
            tags,
            remotes,
            max_parents,
            max_age,
            no_max_parents,
            merges,
            merge,
            min_parents,
            min_age,
            no_min_parents,
            no_merges,
            objects,
            objects_edge,
            objects_edge_aggressive,
            indexed_objects,
            unpacked,
            remove_empty,
            ignore_missing,
            object_names,
            no_object_names,
            filter,
            filter_print_omitted,
            filter_provided_objects,
            parents,
            first_parent,
            children,
            walk_reflogs,
            reflog,
            do_walk,
            no_walk,
            stdin,
            grep_reflog,
            reverse,
            full_history,
            in_commit_order,
            ancestry_path,
            dense,
            sparse,
            show_pulls,
            show_linear_break,
            simplify_merges,
            simplify_by_decoration,
            topo_order,
            date_order,
            author_date_order,
            left_right,
            left_only,
            right_only,
            cherry_pick,
            cherry_mark,
            boundary,
            max_count,
            since,
            since_as_filter,
            until,
            relative_date,
            timestamp,
            date,
            show_signature,
            single_worktree,
            commit_header,
            no_commit_header,
            disk_usage,
            progress,
            no_filter,
            missing,
            use_bitmap_index,
            quiet,
            format,
            pretty,
            revs,
        } => super::history_commands::rev_list(super::history_commands::RevListOptions {
            oneline,
            header,
            graph,
            all,
            exclude,
            exclude_first_parent_only,
            exclude_hidden: exclude_hidden.as_deref(),
            exclude_promisor_objects,
            author: author.as_deref(),
            committer: committer.as_deref(),
            alternate_refs,
            encoding: encoding.as_deref(),
            expand_tabs,
            no_expand_tabs,
            notes,
            no_notes,
            show_notes,
            show_notes_by_default,
            standard_notes,
            no_standard_notes,
            abbrev_commit,
            no_abbrev_commit,
            grep,
            invert_grep,
            all_match,
            regexp_ignore_case,
            basic_regexp,
            extended_regexp,
            fixed_strings,
            perl_regexp,
            bisect,
            bisect_all,
            bisect_vars,
            cherry,
            count,
            glob: glob.as_deref(),
            skip,
            max_parents: max_parents.as_deref(),
            max_age: max_age.as_deref(),
            no_max_parents,
            merges,
            merge,
            min_parents: min_parents.as_deref(),
            min_age: min_age.as_deref(),
            no_min_parents,
            no_merges,
            objects,
            objects_edge,
            objects_edge_aggressive,
            indexed_objects,
            unpacked,
            remove_empty,
            ignore_missing,
            object_names,
            no_object_names,
            filter,
            filter_print_omitted,
            filter_provided_objects,
            parents,
            first_parent,
            children,
            walk_reflogs,
            reflog,
            do_walk,
            no_walk,
            stdin,
            grep_reflog,
            reverse,
            full_history,
            in_commit_order,
            ancestry_path,
            dense,
            sparse,
            show_pulls,
            show_linear_break,
            simplify_merges,
            simplify_by_decoration,
            topo_order,
            date_order,
            author_date_order,
            left_right,
            left_only,
            right_only,
            cherry_pick,
            cherry_mark,
            boundary,
            max_count,
            since: since.as_deref(),
            since_as_filter: since_as_filter.as_deref(),
            until: until.as_deref(),
            relative_date,
            timestamp,
            date: date.as_deref(),
            show_signature,
            single_worktree,
            commit_header,
            no_commit_header,
            disk_usage,
            progress,
            no_filter,
            missing,
            use_bitmap_index,
            quiet,
            format: format.as_deref(),
            pretty: pretty.as_deref(),
            raw_args,
            revs: extend_history_ref_selector_revs(revs, branches, tags, remotes),
        }),
        runtime::Command::MergeBase {
            all,
            is_ancestor,
            octopus,
            commits,
        } => super::history_commands::merge_base(all, is_ancestor, octopus, commits),
        runtime::Command::LastModified {
            recursive,
            show_trees,
            max_depth,
            nul_terminated,
            args,
        } => super::history_commands::last_modified(
            recursive,
            show_trees,
            max_depth,
            nul_terminated,
            args,
        ),
        _ => unreachable!("non-history command dispatched to history"),
    }
}

fn extend_history_ref_selector_revs(
    mut revs: Vec<String>,
    branches: Vec<String>,
    tags: Vec<String>,
    remotes: Vec<String>,
) -> Vec<String> {
    for value in branches {
        if value.is_empty() {
            revs.push("--branches".to_owned());
        } else {
            revs.push(format!("--branches={value}"));
        }
    }
    for value in tags {
        if value.is_empty() {
            revs.push("--tags".to_owned());
        } else {
            revs.push(format!("--tags={value}"));
        }
    }
    for value in remotes {
        if value.is_empty() {
            revs.push("--remotes".to_owned());
        } else {
            revs.push(format!("--remotes={value}"));
        }
    }
    revs
}

fn serialize_reflog_args(
    command: Option<runtime::ReflogCommand>,
    mut args: Vec<String>,
) -> Vec<String> {
    let Some(command) = command else {
        return args;
    };
    let mut out = Vec::new();
    match command {
        runtime::ReflogCommand::Expire(expire) => {
            out.push("expire".to_owned());
            if expire.help {
                out.push("--help".to_owned());
            }
            if let Some(value) = expire.expire {
                out.push(format!("--expire={value}"));
            }
            if let Some(value) = expire.expire_unreachable {
                out.push(format!("--expire-unreachable={value}"));
            }
            if expire.rewrite {
                out.push("--rewrite".to_owned());
            }
            if expire.updateref {
                out.push("--updateref".to_owned());
            }
            if expire.stale_fix {
                out.push("--stale-fix".to_owned());
            }
            if expire.dry_run {
                out.push("--dry-run".to_owned());
            }
            if expire.verbose {
                out.push("--verbose".to_owned());
            }
            if expire.all {
                out.push("--all".to_owned());
            }
            if expire.single_worktree {
                out.push("--single-worktree".to_owned());
            }
            out.extend(expire.refs);
        }
        runtime::ReflogCommand::Delete(delete) => {
            out.push("delete".to_owned());
            if delete.rewrite {
                out.push("--rewrite".to_owned());
            }
            if delete.updateref {
                out.push("--updateref".to_owned());
            }
            if delete.dry_run {
                out.push("--dry-run".to_owned());
            }
            if delete.verbose {
                out.push("--verbose".to_owned());
            }
            out.extend(delete.selectors);
        }
        runtime::ReflogCommand::Drop(drop) => {
            out.push("drop".to_owned());
            if drop.all {
                out.push("--all".to_owned());
            }
            if drop.single_worktree {
                out.push("--single-worktree".to_owned());
            }
            out.extend(drop.refs);
        }
    }
    out.append(&mut args);
    out
}

fn serialize_blame_args(
    help: bool,
    contents: Option<std::path::PathBuf>,
    encoding: Option<String>,
    first_parent: bool,
    ignore_rev: Vec<String>,
    ignore_revs_file: Vec<std::path::PathBuf>,
    reverse: Option<String>,
    revs_file: Option<std::path::PathBuf>,
    mut args: Vec<String>,
) -> Vec<String> {
    let mut out = Vec::new();
    if help {
        out.push("--help".to_owned());
    }
    if let Some(path) = contents {
        out.push("--contents".to_owned());
        out.push(path.to_string_lossy().into_owned());
    }
    if let Some(value) = encoding {
        out.push(format!("--encoding={value}"));
    }
    if first_parent {
        out.push("--first-parent".to_owned());
    }
    for value in ignore_rev {
        out.push("--ignore-rev".to_owned());
        out.push(value);
    }
    for path in ignore_revs_file {
        out.push("--ignore-revs-file".to_owned());
        out.push(path.to_string_lossy().into_owned());
    }
    if let Some(value) = reverse {
        out.push("--reverse".to_owned());
        out.push(value);
    }
    if let Some(path) = revs_file {
        out.push("-S".to_owned());
        out.push(path.to_string_lossy().into_owned());
    }
    out.append(&mut args);
    out
}

#[allow(clippy::too_many_arguments)]
fn serialize_annotate_args(
    help: bool,
    porcelain: bool,
    incremental: bool,
    line_porcelain: bool,
    contents: Option<std::path::PathBuf>,
    date: Option<String>,
    encoding: Option<String>,
    first_parent: bool,
    ignore_rev: Vec<String>,
    ignore_revs_file: Vec<std::path::PathBuf>,
    progress: bool,
    no_progress: bool,
    color_lines: bool,
    color_by_age: bool,
    reverse: Option<String>,
    root: bool,
    show_stats: bool,
    copies: u8,
    line_ranges: Vec<String>,
    moves: u8,
    revs_file: Option<std::path::PathBuf>,
    blank_boundary: bool,
    raw_timestamp: bool,
    mut args: Vec<String>,
) -> Vec<String> {
    let mut out = Vec::new();
    if help {
        out.push("-h".to_owned());
    }
    if porcelain {
        out.push("--porcelain".to_owned());
    }
    if incremental {
        out.push("--incremental".to_owned());
    }
    if line_porcelain {
        out.push("--line-porcelain".to_owned());
    }
    if let Some(value) = date {
        out.push(format!("--date={value}"));
    }
    if progress {
        out.push("--progress".to_owned());
    }
    if no_progress {
        out.push("--no-progress".to_owned());
    }
    if color_lines {
        out.push("--color-lines".to_owned());
    }
    if color_by_age {
        out.push("--color-by-age".to_owned());
    }
    if root {
        out.push("--root".to_owned());
    }
    if show_stats {
        out.push("--show-stats".to_owned());
    }
    for _ in 0..copies {
        out.push("-C".to_owned());
    }
    for value in line_ranges {
        out.push("-L".to_owned());
        out.push(value);
    }
    for _ in 0..moves {
        out.push("-M".to_owned());
    }
    if blank_boundary {
        out.push("-b".to_owned());
    }
    if raw_timestamp {
        out.push("-t".to_owned());
    }
    out.extend(serialize_blame_args(
        false,
        contents,
        encoding,
        first_parent,
        ignore_rev,
        ignore_revs_file,
        reverse,
        revs_file,
        Vec::new(),
    ));
    out.append(&mut args);
    out
}

pub(crate) fn run_replay(options: ReplayOptions) -> std::result::Result<(), runtime::CliError> {
    super::history_commands::run_replay(options)
}

pub(crate) fn run_history(
    command: runtime::HistoryCommand,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    super::history_commands::run_history(command, raw_args)
}

pub(crate) fn run_range_diff(
    no_dual_color: bool,
    no_no_dual_color: bool,
    creation_factor: Option<String>,
    left_only: bool,
    right_only: bool,
    notes: bool,
    no_notes: bool,
    ranges: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::history_commands::range_diff(
        no_dual_color,
        no_no_dual_color,
        creation_factor,
        left_only,
        right_only,
        notes,
        no_notes,
        ranges,
    )
}
