use crate::runtime;

pub(crate) fn dispatch(
    command: runtime::Command,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Quiltimport {
            dry_run,
            author,
            patches,
            series,
            keep_non_patch,
        } => super::import_commands::quiltimport(
            dry_run,
            author.as_deref(),
            patches,
            series,
            keep_non_patch,
        ),
        runtime::Command::FastExport {
            all,
            anonymize,
            anonymize_map,
            progress,
            signed_tags,
            tag_of_filtered_object,
            reencode,
            export_marks,
            import_marks,
            import_marks_if_exists,
            fake_missing_tagger,
            full_tree,
            use_done_feature,
            no_data,
            refspec,
            reference_excluded_parents,
            show_original_ids,
            mark_tags,
            detect_copies,
            detect_renames,
            refs,
        } => {
            super::import_commands::fast_export(super::import_commands::FastExportOptions {
                all: all > 0,
                anonymize,
                anonymize_map,
                progress,
                signed_tags,
                tag_of_filtered_object,
                reencode,
                export_marks,
                import_marks,
                import_marks_if_exists,
                fake_missing_tagger,
                full_tree,
                use_done_feature,
                no_data,
                refspec,
                reference_excluded_parents,
                show_original_ids,
                mark_tags,
                detect_copies,
                detect_renames,
                refs,
            })
        }
        runtime::Command::FastImport {
            date_format,
            quiet,
            stats,
            force,
            done,
            allow_unsafe_features,
            active_branches,
            depth,
            big_file_threshold,
            cat_blob_fd,
            export_marks,
            export_pack_edges,
            import_marks,
            import_marks_if_exists,
            max_pack_size,
            no_relative_marks,
            relative_marks,
            rewrite_submodules_from,
            rewrite_submodules_to,
        } => {
            let (quiet, stats) =
                super::import_commands::resolve_fast_import_stats_mode(raw_args, quiet, stats);
            super::import_commands::fast_import(super::import_commands::FastImportOptions {
                date_format,
                quiet,
                stats,
                force,
                done,
                allow_unsafe_features,
                active_branches,
                depth,
                big_file_threshold,
                cat_blob_fd,
                export_marks,
                export_pack_edges,
                import_marks,
                import_marks_if_exists,
                max_pack_size,
                no_relative_marks,
                relative_marks,
                rewrite_submodules_from,
                rewrite_submodules_to,
            })
        }
        _ => unreachable!("non-import command dispatched to import"),
    }
}
