use crate::runtime;

pub(crate) fn dispatch(
    command: runtime::Command,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::InterpretTrailers {
            in_place,
            trim_empty,
            where_,
            no_where: _,
            if_exists,
            no_if_exists: _,
            if_missing,
            no_if_missing: _,
            only_trailers,
            only_input,
            unfold,
            parse,
            no_divider,
            divider,
            trailers,
            files,
        } => super::mail_commands::interpret_trailers(runtime::InterpretTrailersOptions {
            in_place,
            trim_empty,
            where_: where_.as_deref(),
            if_exists: if_exists.as_deref(),
            if_missing: if_missing.as_deref(),
            only_trailers: only_trailers || parse,
            only_input: only_input || parse,
            unfold: unfold || parse,
            no_divider: no_divider && !divider,
            trailers,
            files,
        }),
        runtime::Command::Mailsplit {
            precision,
            first,
            keep_from,
            keep_cr,
            mboxrd: _,
            output,
            paths,
        } => super::mail_commands::mailsplit(
            precision,
            first,
            keep_from > 0,
            keep_cr > 0,
            output,
            paths,
        ),
        runtime::Command::Mailinfo {
            keep_subject,
            keep_non_patch_brackets,
            message_id,
            recode: _,
            no_recode: _,
            encoding: _,
            scissors: _,
            no_scissors: _,
            quoted_cr: _,
            msg,
            patch,
        } => super::mail_commands::mailinfo(
            keep_subject,
            keep_non_patch_brackets,
            message_id,
            msg,
            patch,
        ),
        runtime::Command::FmtMergeMsg {
            log,
            no_log,
            summary,
            no_summary,
            message,
            into_name,
            file,
        } => {
            let (log, no_log) =
                resolve_fmt_merge_msg_summary_aliases(raw_args, log, no_log, summary, no_summary);
            super::mail_commands::fmt_merge_msg(
                log,
                no_log,
                message.as_deref(),
                into_name.as_deref(),
                file,
            )
        }
        runtime::Command::Am {
            quiet,
            signoff,
            utf8,
            no_utf8,
            keep,
            keep_non_patch,
            keep_cr,
            no_keep_cr,
            message_id,
            no_message_id,
            scissors,
            no_scissors,
            quoted_cr,
            three_way,
            no_three_way,
            ignore_space_change,
            ignore_whitespace,
            whitespace,
            context,
            strip,
            directory,
            include,
            exclude,
            patch_format,
            interactive,
            ignore_date,
            empty,
            reject,
            gpg_sign,
            no_gpg_sign,
            rerere_autoupdate,
            no_rerere_autoupdate,
            resolvemsg,
            no_verify,
            committer_date_is_author_date,
            allow_empty,
            abort,
            quit,
            skip,
            continue_,
            resolved,
            retry,
            show_current_patch,
            patches,
        } => super::mail_commands::am(
            super::mail_commands::AmOptions {
                quiet,
                signoff,
                utf8,
                no_utf8,
                keep,
                keep_non_patch,
                keep_cr,
                no_keep_cr,
                message_id,
                no_message_id,
                scissors,
                no_scissors,
                quoted_cr,
                three_way,
                no_three_way,
                ignore_space_change,
                ignore_whitespace,
                whitespace,
                context,
                strip,
                directory,
                include,
                exclude,
                patch_format,
                interactive,
                ignore_date,
                empty,
                reject,
                gpg_sign,
                no_gpg_sign,
                rerere_autoupdate,
                no_rerere_autoupdate,
                resolvemsg,
                no_verify,
                committer_date_is_author_date,
                allow_empty,
                abort,
                quit,
                skip,
                continue_,
                resolved,
                retry,
                show_current_patch,
            },
            patches,
        ),
        runtime::Command::FormatPatch {
            output_directory,
            output,
            stdout,
            abbrev: _,
            always: _,
            anchored: _,
            binary: _,
            break_rewrites: _,
            color: _,
            color_moved: _,
            color_moved_ws: _,
            compact_summary: _,
            check,
            default_prefix: _,
            diff_algorithm: _,
            diff_filter: _,
            dst_prefix: _,
            exit_code: _,
            ext_diff: _,
            find_copies: _,
            find_copies_harder: _,
            find_renames: _,
            function_context: _,
            histogram: _,
            ignore_all_space: _,
            ignore_blank_lines: _,
            ignore_cr_at_eol: _,
            ignore_space_at_eol: _,
            ignore_space_change: _,
            ignore_matching_lines: _,
            ignore_submodules: _,
            indent_heuristic: _,
            inter_hunk_context: _,
            irreversible_delete: _,
            ita_invisible_in_index: _,
            pickaxe_string: _,
            pickaxe_regex: _,
            pickaxe_regex_mode: _,
            pickaxe_all: _,
            find_object: _,
            rename_limit_short: _,
            nul_terminated,
            reverse,
            submodule,
            order_file,
            skip_to,
            rotate_to,
            word_diff,
            color_words,
            word_diff_regex,
            line_prefix: _,
            minimal: _,
            no_attach: _,
            no_binary: _,
            no_cover_letter: _,
            cover_from_description,
            description_file,
            no_ext_diff: _,
            no_textconv: _,
            no_color: _,
            no_color_moved: _,
            no_color_moved_ws: _,
            no_indent_heuristic: _,
            name_only,
            name_status,
            no_notes: _,
            no_prefix,
            no_relative: _,
            no_rename_empty: _,
            no_renames: _,
            no_thread: _,
            thread,
            notes: _,
            to,
            cc,
            add_header,
            in_reply_to,
            from,
            force_in_body_from,
            no_force_in_body_from,
            output_indicator_context: _,
            output_indicator_new: _,
            output_indicator_old: _,
            base,
            no_base,
            patience: _,
            text: _,
            textconv: _,
            stat: _,
            patch: _,
            patch_with_raw,
            patch_with_stat: _,
            no_stat,
            no_patch,
            numstat,
            dirstat,
            dirstat_short,
            cumulative,
            dirstat_by_file,
            shortstat,
            raw,
            summary,
            filename_max_length,
            ignore_if_in_upstream,
            interdiff,
            range_diff,
            creation_factor,
            separate_merges,
            combined_merges,
            tree_in_diff,
            first_parent_diff,
            diff_merges,
            no_diff_merges,
            combined_all_paths,
            remerge_diff,
            progress: _,
            quiet: _,
            relative: _,
            rename_empty: _,
            root: _,
            src_prefix: _,
            full_index,
            unified: _,
            ws_error_highlight: _,
            break_rewrites_short: _,
            find_copies_short: _,
            irreversible_delete_short: _,
            find_renames_short: _,
            intent_to_add_short: _,
            function_context_short: _,
            attach,
            inline,
            suffix,
            subject_prefix,
            keep_subject,
            no_numbered,
            numbered,
            numbered_files,
            start_number,
            cover_letter,
            signoff,
            signature,
            signature_file,
            no_signature,
            encode_email_headers,
            no_encode_email_headers,
            reroll_count,
            rfc,
            zero_commit,
            one,
            revs,
        } => super::mail_commands::format_patch(
            output_directory,
            output,
            stdout,
            check,
            name_only,
            name_status,
            format_patch_uses_short_patch_alias(raw_args),
            patch_with_raw,
            no_stat,
            no_patch,
            numstat,
            dirstat.as_deref(),
            dirstat_short.as_deref(),
            cumulative,
            dirstat_by_file.as_deref(),
            shortstat,
            raw,
            summary,
            separate_merges,
            combined_merges,
            tree_in_diff,
            first_parent_diff,
            diff_merges.as_deref(),
            no_diff_merges,
            combined_all_paths,
            remerge_diff,
            full_index,
            nul_terminated,
            no_prefix,
            reverse,
            submodule.as_deref(),
            order_file.as_deref(),
            skip_to.as_deref(),
            rotate_to.as_deref(),
            word_diff.as_deref(),
            color_words.as_deref(),
            word_diff_regex.as_deref(),
            attach,
            inline,
            suffix.as_deref(),
            subject_prefix.as_deref(),
            keep_subject,
            no_numbered,
            numbered,
            numbered_files,
            start_number.as_deref(),
            cover_letter,
            thread,
            to,
            cc,
            add_header,
            in_reply_to.as_deref(),
            from.as_deref(),
            force_in_body_from,
            no_force_in_body_from,
            cover_from_description.as_deref(),
            description_file.as_deref(),
            signoff,
            signature.as_deref(),
            signature_file.as_deref(),
            no_signature,
            encode_email_headers,
            no_encode_email_headers,
            reroll_count.as_deref(),
            rfc.as_deref(),
            base.as_deref(),
            no_base,
            filename_max_length.as_deref(),
            ignore_if_in_upstream,
            interdiff.as_deref(),
            range_diff.as_deref(),
            creation_factor.as_deref(),
            zero_commit,
            one,
            revs,
        ),
        runtime::Command::SendEmail {
            dump_aliases,
            translate_aliases,
            bcc,
            cc_cover,
            chain_reply_to,
            cc,
            from,
            reply_to,
            identity,
            mailmap,
            no_bcc,
            no_cc,
            no_chain_reply_to,
            no_identity,
            no_mailmap,
            no_signed_off_by_cc,
            smtp_auth,
            smtp_debug,
            smtp_domain,
            smtp_pass,
            smtp_server,
            smtp_server_port,
            subject,
            suppress_cc,
            suppress_from,
            thread,
            to,
            to_cover,
            force,
            format_patch,
            no_format_patch,
            no_smtp_auth,
            no_suppress_from,
            no_thread,
            no_to_cover,
            no_validate,
            validate,
            xmailer,
            args,
        } => super::mail_commands::send_email(super::mail_commands::SendEmailCommandOptions {
            dump_aliases,
            translate_aliases,
            bcc,
            cc_cover,
            chain_reply_to,
            cc,
            from,
            reply_to,
            identity,
            mailmap,
            no_bcc,
            no_cc,
            no_chain_reply_to,
            no_identity,
            no_mailmap,
            no_signed_off_by_cc,
            smtp_auth,
            smtp_debug,
            smtp_domain,
            smtp_pass,
            smtp_server,
            smtp_server_port,
            subject,
            suppress_cc,
            suppress_from,
            thread,
            to,
            to_cover,
            force,
            format_patch,
            no_format_patch,
            no_smtp_auth,
            no_suppress_from,
            no_thread,
            no_to_cover,
            no_validate,
            validate,
            xmailer,
            args,
        }),
        runtime::Command::ImapSend {
            verbose,
            quiet,
            folder,
            list,
            curl,
            no_curl,
        } => super::mail_commands::imap_send(super::mail_commands::ImapSendOptions {
            verbose,
            quiet,
            folder,
            list,
            curl,
            no_curl,
        }),
        _ => unreachable!("non-mail command dispatched to mail"),
    }
}

fn resolve_fmt_merge_msg_summary_aliases(
    raw_args: &[String],
    log: Option<usize>,
    no_log: bool,
    summary: Option<usize>,
    no_summary: bool,
) -> (Option<usize>, bool) {
    if log.is_none() && !no_log && summary.is_none() && !no_summary {
        return (None, false);
    }

    let mut resolved_log = log;
    let mut resolved_no_log = no_log;
    for arg in raw_args {
        if let Some(value) = arg.strip_prefix("--log=") {
            resolved_log = value.parse().ok();
            resolved_no_log = false;
            continue;
        }
        if arg == "--log" {
            resolved_log = log.or(Some(20));
            resolved_no_log = false;
            continue;
        }
        if let Some(value) = arg.strip_prefix("--summary=") {
            resolved_log = value.parse().ok();
            resolved_no_log = false;
            continue;
        }
        if arg == "--summary" {
            resolved_log = summary.or(Some(20));
            resolved_no_log = false;
            continue;
        }
        if arg == "--no-log" || arg == "--no-summary" {
            resolved_log = None;
            resolved_no_log = true;
        }
    }
    (resolved_log, resolved_no_log)
}

fn format_patch_uses_short_patch_alias(raw_args: &[String]) -> bool {
    raw_args.iter().any(|arg| arg == "-p")
}
