use crate::runtime;

pub(crate) fn dispatch(command: runtime::Command) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::InterpretTrailers {
            in_place,
            trim_empty,
            where_,
            if_exists,
            if_missing,
            only_trailers,
            only_input,
            unfold,
            parse,
            no_divider,
            divider,
            trailers,
            files,
        } => super::mail_commands::interpret_trailers(runtime::InterpretTrailersOptions {
            in_place,
            trim_empty,
            where_: where_.as_deref(),
            if_exists: if_exists.as_deref(),
            if_missing: if_missing.as_deref(),
            only_trailers: only_trailers || parse,
            only_input: only_input || parse,
            unfold: unfold || parse,
            no_divider: no_divider && !divider,
            trailers,
            files,
        }),
        runtime::Command::Mailsplit {
            precision,
            first,
            keep_from,
            keep_cr,
            output,
            paths,
        } => super::mail_commands::mailsplit(precision, first, keep_from, keep_cr, output, paths),
        runtime::Command::Mailinfo {
            keep_subject,
            keep_non_patch_brackets,
            message_id,
            recode: _,
            no_recode: _,
            encoding: _,
            scissors: _,
            quoted_cr: _,
            msg,
            patch,
        } => super::mail_commands::mailinfo(
            keep_subject,
            keep_non_patch_brackets,
            message_id,
            msg,
            patch,
        ),
        runtime::Command::FmtMergeMsg {
            log,
            no_log,
            message,
            into_name,
            file,
        } => super::mail_commands::fmt_merge_msg(
            log,
            no_log,
            message.as_deref(),
            into_name.as_deref(),
            file,
        ),
        runtime::Command::Am { patches } => super::mail_commands::am(patches),
        runtime::Command::FormatPatch {
            output_directory,
            stdout,
            attach,
            inline,
            suffix,
            subject_prefix,
            no_numbered,
            numbered,
            numbered_files,
            cover_letter,
            one,
            revs,
        } => super::mail_commands::format_patch(
            output_directory,
            stdout,
            attach,
            inline,
            suffix.as_deref(),
            subject_prefix.as_deref(),
            no_numbered,
            numbered,
            numbered_files,
            cover_letter,
            one,
            revs,
        ),
        runtime::Command::SendEmail {
            dump_aliases,
            translate_aliases,
            args,
        } => super::mail_commands::send_email(dump_aliases, translate_aliases, args),
        runtime::Command::ImapSend {
            verbose,
            quiet,
            folder,
            list,
            curl,
            no_curl,
        } => super::mail_commands::imap_send(super::mail_commands::ImapSendOptions {
            verbose,
            quiet,
            folder,
            list,
            curl,
            no_curl,
        }),
        _ => unreachable!("non-mail command dispatched to mail"),
    }
}
