use crate::runtime;

pub(crate) fn dispatch(command: runtime::Command) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Maintenance {
            operation,
            auto,
            no_auto,
            schedule,
            no_schedule,
            scheduler,
            config_file,
            force,
            quiet,
            no_quiet,
            tasks,
        } => super::maintenance_commands::maintenance(
            super::maintenance_commands::MaintenanceOptions {
                operation: &operation,
                auto: auto && !no_auto,
                schedule: schedule.as_deref(),
                no_schedule,
                scheduler: scheduler.as_deref(),
                config_file: config_file.as_deref(),
                force,
                quiet: quiet && !no_quiet,
                tasks,
            },
        ),
        runtime::Command::PrunePacked {
            dry_run,
            no_dry_run,
            quiet,
            no_quiet,
        } => {
            super::maintenance_commands::prune_packed_command(
                dry_run > 0 && no_dry_run == 0,
                quiet > 0 && no_quiet == 0,
            )
        }
        runtime::Command::Repack {
            all,
            all_and_loosen_unreachable,
            delete_redundant,
            quiet,
            no_update_server_info,
            no_reuse_delta,
            no_reuse_object,
            delta_islands,
            delta_islands_short,
            keep_unreachable_short,
            keep_unreachable,
            cruft,
            cruft_expiration,
            expire_to,
            local,
            pack_kept_objects,
            write_bitmap_index,
            no_write_bitmap_index,
            write_midx,
            no_write_midx,
            window,
            window_memory,
            depth,
            geometric,
            threads,
            max_pack_size,
            max_cruft_size,
            filter,
            filter_to,
            unpack_unreachable,
            keep_pack,
        } => super::maintenance_commands::repack_command(
            all > 0,
            all_and_loosen_unreachable > 0,
            delete_redundant > 0,
            quiet > 0,
            no_update_server_info > 0,
            no_reuse_delta > 0,
            no_reuse_object > 0,
            delta_islands || delta_islands_short > 0,
            keep_unreachable || keep_unreachable_short > 0,
            cruft > 0,
            cruft_expiration.into_iter().last(),
            expire_to.into_iter().last(),
            local > 0,
            pack_kept_objects,
            write_bitmap_index > 0,
            no_write_bitmap_index,
            write_midx > 0,
            no_write_midx,
            window,
            window_memory,
            depth,
            geometric,
            threads,
            max_pack_size,
            max_cruft_size,
            filter.into_iter().last(),
            filter_to.into_iter().last(),
            unpack_unreachable,
            keep_pack,
        ),
        runtime::Command::Gc {
            prune,
            no_prune,
            auto,
            detach,
            no_detach,
            cruft,
            no_cruft,
            max_cruft_size,
            aggressive,
            quiet,
            force,
            keep_largest_pack,
        } => super::maintenance_commands::gc_command(
            prune,
            no_prune,
            auto,
            detach,
            no_detach,
            cruft,
            no_cruft,
            max_cruft_size,
            aggressive,
            quiet,
            force,
            keep_largest_pack,
        ),
        runtime::Command::Prune { args } => super::maintenance_commands::prune_command(args),
        command => {
            unreachable!("non-maintenance command routed to maintenance dispatcher: {command:?}")
        }
    }
}
