use crate::runtime;

pub(crate) fn dispatch(command: runtime::Command) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Apply {
            allow_empty,
            allow_binary_replacement,
            apply,
            binary,
            check,
            cached,
            stat,
            numstat,
            summary,
            index,
            recount,
            quiet,
            verbose,
            unsafe_paths,
            unidiff_zero,
            ignore_space_change,
            ignore_whitespace,
            whitespace,
            strip,
            context,
            z,
            reject,
            three_way,
            ours,
            theirs,
            union,
            reverse,
            patches,
        } => super::patch_commands::apply(super::patch_commands::ApplyOptions {
            allow_empty,
            allow_binary_replacement,
            apply,
            binary,
            check,
            cached,
            stat,
            numstat,
            summary,
            index,
            recount,
            quiet,
            verbose,
            unsafe_paths,
            unidiff_zero,
            ignore_space_change,
            ignore_whitespace,
            whitespace,
            strip,
            context,
            z,
            reject,
            three_way,
            ours,
            theirs,
            union,
            reverse,
            patches,
        }),
        _ => unreachable!("non-patch command dispatched to patch"),
    }
}
