use crate::runtime;

pub(crate) fn dispatch(command: runtime::Command) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Apply {
            allow_empty,
            allow_binary_replacement,
            apply,
            binary,
            check,
            cached,
            stat,
            numstat,
            summary,
            build_fake_ancestor,
            index,
            recount,
            quiet,
            verbose,
            unsafe_paths,
            unidiff_zero,
            ignore_space_change,
            ignore_whitespace,
            inaccurate_eof,
            whitespace,
            strip,
            context,
            directory,
            include,
            exclude,
            intent_to_add,
            no_add,
            z,
            reject,
            three_way,
            ours,
            theirs,
            union,
            reverse,
            patches,
        } => super::patch_commands::apply(super::patch_commands::ApplyOptions {
            allow_empty,
            allow_binary_replacement,
            apply,
            binary,
            check,
            cached,
            stat,
            numstat,
            summary,
            build_fake_ancestor,
            index,
            recount,
            quiet,
            verbose,
            unsafe_paths,
            unidiff_zero,
            ignore_space_change,
            ignore_whitespace,
            inaccurate_eof: inaccurate_eof > 0,
            whitespace,
            strip,
            context,
            directory: directory.last().cloned(),
            include,
            exclude,
            intent_to_add,
            no_add: no_add > 0,
            z,
            reject,
            three_way: three_way > 0,
            ours,
            theirs,
            union,
            reverse,
            patches,
        }),
        _ => unreachable!("non-patch command dispatched to patch"),
    }
}
