use crate::runtime;

pub(crate) fn dispatch(
    command: runtime::Command,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Remote { verbose, command } => run_remote(verbose, command),
        runtime::Command::PackRefs {
            all,
            prune,
            no_prune,
        } => run_pack_refs(all, prune, no_prune),
        runtime::Command::UpdateRef {
            delete,
            no_deref,
            deref: _,
            stdin,
            nul_terminated,
            message,
            create_reflog,
            no_create_reflog,
            batch_updates,
            no_batch_updates,
            name,
            newvalue,
        } => run_update_ref(
            delete,
            no_deref,
            stdin,
            nul_terminated,
            message,
            create_reflog && !no_create_reflog,
            batch_updates && !no_batch_updates,
            name,
            newvalue,
        ),
        runtime::Command::SymbolicRef {
            quiet,
            short,
            no_recurse,
            name,
            target,
        } => run_symbolic_ref(quiet, short, no_recurse, name, target),
        runtime::Command::Refs { command } => run_refs(command),
        runtime::Command::Repo { command } => run_repo(command),
        runtime::Command::ShowRef {
            quiet,
            head,
            heads,
            tags,
            hash,
            abbrev,
            verify,
            exists,
            refs,
        } => run_show_ref(quiet, head, heads, tags, hash, abbrev, verify, exists, refs),
        runtime::Command::ForEachRef {
            format,
            sort,
            patterns,
        } => run_for_each_ref(format, sort, patterns),
        runtime::Command::LsTree {
            recursive,
            show_trees,
            name_only,
            treeish,
            paths,
        } => run_ls_tree(recursive, show_trees, name_only, treeish, paths),
        runtime::Command::Branch {
            help,
            remotes,
            all,
            list,
            force,
            verbose,
            abbrev,
            no_abbrev,
            column,
            create_reflog,
            no_create_reflog,
            show_current,
            edit_description,
            delete,
            force_delete,
            move_branch,
            force_move,
            copy_branch,
            force_copy,
            set_upstream_to,
            unset_upstream,
            track,
            no_track,
            sort,
            no_sort,
            contains,
            merged,
            no_merged,
            name,
            start_point,
            extra_args,
        } => run_branch(
            help,
            remotes,
            all,
            list,
            force,
            verbose,
            abbrev,
            no_abbrev,
            column,
            create_reflog && !no_create_reflog,
            show_current,
            edit_description,
            delete,
            force_delete,
            move_branch,
            force_move,
            copy_branch,
            force_copy,
            set_upstream_to,
            unset_upstream,
            track,
            no_track,
            sort,
            no_sort,
            contains,
            merged,
            no_merged,
            name,
            start_point,
            extra_args,
        ),
        runtime::Command::Tag {
            delete,
            verify,
            list,
            force,
            annotate,
            messages,
            contains,
            no_contains,
            merged,
            no_merged,
            sort,
            format,
            args,
        } => run_tag(
            delete,
            verify,
            list,
            force,
            annotate,
            messages,
            contains,
            no_contains,
            merged,
            no_merged,
            sort,
            format,
            args,
        ),
        runtime::Command::Replace {
            list,
            delete,
            force,
            format,
            edit,
            graft,
            convert_graft_file,
            raw,
            no_raw,
            args,
        } => run_replace(
            list,
            delete,
            force,
            format,
            edit,
            graft,
            convert_graft_file,
            raw && !no_raw,
            args,
        ),
        runtime::Command::PatchId {
            stable,
            unstable,
            verbatim,
        } => run_patch_id(stable, unstable, verbatim),
        runtime::Command::RevParse {
            short,
            abbrev_ref,
            verify,
            quiet,
            symbolic_full_name,
            bisect,
            path_format,
            since,
            until,
            show_object_format,
            show_ref_format,
            show_toplevel,
            show_prefix,
            show_cdup,
            show_superproject_working_tree,
            git_dir,
            absolute_git_dir,
            git_common_dir,
            git_paths,
            is_inside_git_dir,
            is_inside_work_tree,
            is_bare_repository,
            is_shallow_repository,
            revs,
        } => run_rev_parse(
            short,
            abbrev_ref,
            verify,
            quiet,
            symbolic_full_name,
            bisect,
            path_format,
            since,
            until,
            show_object_format,
            show_ref_format,
            show_toplevel,
            show_prefix,
            show_cdup,
            show_superproject_working_tree,
            git_dir,
            absolute_git_dir,
            git_common_dir,
            git_paths,
            is_inside_git_dir,
            is_inside_work_tree,
            is_bare_repository,
            is_shallow_repository,
            revs,
            raw_args,
        ),
        _ => unreachable!("non-reference command dispatched to reference"),
    }
}

pub(crate) fn run_remote(
    verbose: bool,
    command: Option<runtime::RemoteCommand>,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::remote_command(verbose, command)
}

pub(crate) fn run_pack_refs(
    all: bool,
    prune: bool,
    no_prune: bool,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::pack_refs(all, prune, no_prune)
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn run_update_ref(
    delete: bool,
    no_deref: bool,
    stdin: bool,
    nul_terminated: bool,
    message: Option<String>,
    create_reflog: bool,
    batch_updates: bool,
    name: Option<String>,
    newvalue: Option<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::update_ref(super::reference_commands::UpdateRefCommandOptions {
        delete,
        no_deref,
        stdin,
        nul_terminated,
        message: message.as_deref(),
        create_reflog,
        batch_updates,
        name: name.as_deref(),
        newvalue: newvalue.as_deref(),
    })
}

pub(crate) fn run_symbolic_ref(
    quiet: bool,
    short: bool,
    no_recurse: bool,
    name: String,
    target: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::symbolic_ref(quiet, short, no_recurse, &name, target)
}

pub(crate) fn run_refs(
    command: runtime::RefsCommand,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::refs_command(command)
}

pub(crate) fn run_repo(
    command: runtime::RepoCommand,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::repo_command(command)
}

pub(crate) fn run_show_ref(
    quiet: bool,
    head: bool,
    heads: bool,
    tags: bool,
    hash: Option<usize>,
    abbrev: Option<usize>,
    verify: bool,
    exists: bool,
    refs: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::show_ref(
        quiet, head, heads, tags, hash, abbrev, verify, exists, refs,
    )
}

pub(crate) fn run_for_each_ref(
    format: Option<String>,
    sort: Vec<String>,
    patterns: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::for_each_ref(format.as_deref(), sort, patterns)
}

pub(crate) fn run_ls_tree(
    recursive: bool,
    show_trees: bool,
    name_only: bool,
    treeish: String,
    paths: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::ls_tree_command(recursive, show_trees, name_only, &treeish, paths)
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn run_branch(
    help: bool,
    remotes: bool,
    all: bool,
    list: bool,
    force: bool,
    verbose: u8,
    abbrev: Option<usize>,
    no_abbrev: bool,
    column: Option<String>,
    create_reflog: bool,
    show_current: bool,
    edit_description: bool,
    delete: bool,
    force_delete: bool,
    move_branch: bool,
    force_move: bool,
    copy_branch: bool,
    force_copy: bool,
    set_upstream_to: Option<String>,
    unset_upstream: bool,
    track: Option<String>,
    no_track: bool,
    sort: Vec<String>,
    no_sort: bool,
    contains: Option<String>,
    merged: Option<String>,
    no_merged: Option<String>,
    name: Option<String>,
    start_point: Option<String>,
    extra_args: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::branch_command(
        help,
        remotes,
        all,
        list,
        force,
        verbose,
        abbrev,
        no_abbrev,
        column,
        create_reflog,
        show_current,
        edit_description,
        delete,
        force_delete,
        move_branch,
        force_move,
        copy_branch,
        force_copy,
        set_upstream_to,
        unset_upstream,
        track,
        no_track,
        sort,
        no_sort,
        contains,
        merged,
        no_merged,
        name,
        start_point,
        extra_args,
    )
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn run_tag(
    delete: bool,
    verify: bool,
    list: bool,
    force: bool,
    annotate: bool,
    messages: Vec<String>,
    contains: Option<String>,
    no_contains: Option<String>,
    merged: Option<String>,
    no_merged: Option<String>,
    sort: Vec<String>,
    format: Option<String>,
    args: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::tag_command(
        delete,
        verify,
        list,
        force,
        annotate,
        messages,
        contains,
        no_contains,
        merged,
        no_merged,
        sort,
        format,
        args,
    )
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn run_replace(
    list: bool,
    delete: bool,
    force: bool,
    format: Option<String>,
    edit: bool,
    graft: bool,
    convert_graft_file: bool,
    raw: bool,
    args: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::replace(super::reference_commands::ReplaceOptions {
        list,
        delete,
        force,
        format,
        edit,
        graft,
        convert_graft_file,
        raw,
        args,
    })
}

pub(crate) fn run_patch_id(
    stable: bool,
    unstable: bool,
    verbatim: bool,
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::patch_id(stable, unstable, verbatim)
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn run_rev_parse(
    short: Option<usize>,
    abbrev_ref: Option<String>,
    verify: bool,
    quiet: bool,
    symbolic_full_name: bool,
    bisect: bool,
    path_format: Vec<String>,
    since: Vec<String>,
    until: Vec<String>,
    show_object_format: Vec<String>,
    show_ref_format: bool,
    show_toplevel: bool,
    show_prefix: bool,
    show_cdup: bool,
    show_superproject_working_tree: bool,
    git_dir: bool,
    absolute_git_dir: bool,
    git_common_dir: bool,
    git_paths: Vec<std::path::PathBuf>,
    is_inside_git_dir: bool,
    is_inside_work_tree: bool,
    is_bare_repository: bool,
    is_shallow_repository: bool,
    revs: Vec<String>,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    super::reference_commands::rev_parse_command(
        short,
        abbrev_ref,
        verify,
        quiet,
        symbolic_full_name,
        bisect,
        path_format,
        since,
        until,
        show_object_format,
        show_ref_format,
        show_toplevel,
        show_prefix,
        show_cdup,
        show_superproject_working_tree,
        git_dir,
        absolute_git_dir,
        git_common_dir,
        git_paths,
        is_inside_git_dir,
        is_inside_work_tree,
        is_bare_repository,
        is_shallow_repository,
        revs,
        raw_args,
    )
}
