use crate::runtime;

pub(crate) fn dispatch(command: runtime::Command) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::CherryPick {
            abort,
            continue_,
            ff,
            no_commit,
            mainline,
            record_origin,
            allow_empty,
            allow_empty_message,
            keep_redundant_commits,
            empty,
            signoff,
            edit,
            cleanup,
            rerere_autoupdate,
            no_rerere_autoupdate,
            strategy,
            strategy_option,
            gpg_sign,
            no_gpg_sign,
            commits,
            ..
        } => super::sequencer_commands::sequencer_command(
            super::sequencer_commands::SequencerCommandOptions {
                command: "cherry-pick",
                abort,
                continue_,
                ff,
                no_commit,
                mainline,
                record_origin: record_origin > 0,
                allow_empty: allow_empty > 0,
                allow_empty_message,
                keep_redundant_commits: keep_redundant_commits > 0,
                empty: empty.as_deref(),
                reference: false,
                signoff: signoff > 0,
                edit: edit > 0,
                no_edit: false,
                cleanup: cleanup.as_deref(),
                rerere_autoupdate: rerere_autoupdate > 0,
                no_rerere_autoupdate: no_rerere_autoupdate > 0,
                strategy: strategy.as_deref(),
                strategy_option,
                gpg_sign,
                no_gpg_sign,
                commits,
            },
        ),
        runtime::Command::Revert {
            abort,
            continue_,
            no_commit,
            mainline,
            reference,
            signoff,
            edit,
            no_edit,
            cleanup,
            rerere_autoupdate,
            no_rerere_autoupdate,
            strategy,
            strategy_option,
            gpg_sign,
            no_gpg_sign,
            commits,
            ..
        } => super::sequencer_commands::sequencer_command(
            super::sequencer_commands::SequencerCommandOptions {
                command: "revert",
                abort,
                continue_,
                ff: false,
                no_commit,
                mainline,
                record_origin: false,
                allow_empty: false,
                allow_empty_message: false,
                keep_redundant_commits: false,
                empty: None,
                reference: reference > 0,
                signoff: signoff > 0,
                edit: edit > 0,
                no_edit: no_edit > 0,
                cleanup: cleanup.as_deref(),
                rerere_autoupdate: rerere_autoupdate > 0,
                no_rerere_autoupdate: no_rerere_autoupdate > 0,
                strategy: strategy.as_deref(),
                strategy_option,
                gpg_sign,
                no_gpg_sign,
                commits,
            },
        ),
        runtime::Command::Bisect { args } => super::sequencer_commands::bisect(args),
        runtime::Command::Rerere { args } => super::sequencer_commands::rerere(args),
        runtime::Command::Rebase {
            abort,
            apply,
            allow_empty_message: _allow_empty_message,
            autosquash: _autosquash,
            autostash: _autostash,
            continue_,
            committer_date_is_author_date,
            context_lines,
            empty: _empty,
            exec,
            gpg_sign,
            ignore_date,
            interactive,
            ignore_whitespace: _ignore_whitespace,
            force_rebase: _force_rebase,
            fork_point: _fork_point,
            keep_base,
            keep_empty: _keep_empty,
            merge: _merge,
            no_autosquash: _no_autosquash,
            no_autostash: _no_autostash,
            no_gpg_sign,
            no_stat: _no_stat,
            no_ff: _no_ff,
            no_fork_point: _no_fork_point,
            no_keep_empty: _no_keep_empty,
            no_reapply_cherry_picks: _no_reapply_cherry_picks,
            no_reschedule_failed_exec: _no_reschedule_failed_exec,
            rebase_merges,
            no_rebase_merges,
            no_rerere_autoupdate: _no_rerere_autoupdate,
            no_update_refs: _no_update_refs,
            no_verify: _no_verify,
            onto,
            quiet,
            reapply_cherry_picks: _reapply_cherry_picks,
            reschedule_failed_exec: _reschedule_failed_exec,
            reset_author_date,
            rerere_autoupdate: _rerere_autoupdate,
            signoff,
            strategy: _strategy,
            strategy_option: _strategy_option,
            stat,
            short_exec,
            update_refs: _update_refs,
            verbose,
            verify: _verify,
            whitespace,
            args,
        } => super::sequencer_commands::rebase(
            abort,
            continue_,
            onto.as_deref(),
            args,
            rebase_merges && !no_rebase_merges,
            interactive,
            quiet,
            signoff,
            committer_date_is_author_date,
            ignore_date || reset_author_date,
            apply,
            keep_base,
            [exec, short_exec].concat(),
            gpg_sign,
            no_gpg_sign,
            context_lines,
            stat,
            verbose,
            whitespace.as_deref(),
        ),
        _ => unreachable!("non-sequencer command dispatched to sequencer"),
    }
}
