use crate::runtime;

pub(crate) fn dispatch(command: runtime::Command) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::CherryPick {
            abort,
            continue_,
            ff,
            no_commit,
            mainline,
            record_origin,
            allow_empty,
            allow_empty_message,
            keep_redundant_commits,
            empty,
            signoff,
            edit,
            cleanup,
            rerere_autoupdate,
            no_rerere_autoupdate,
            strategy,
            strategy_option,
            gpg_sign,
            no_gpg_sign,
            commits,
            ..
        } => super::sequencer_commands::sequencer_command(
            super::sequencer_commands::SequencerCommandOptions {
                command: "cherry-pick",
                abort,
                continue_,
                ff,
                no_commit,
                mainline,
                record_origin: record_origin > 0,
                allow_empty: allow_empty > 0,
                allow_empty_message,
                keep_redundant_commits: keep_redundant_commits > 0,
                empty: empty.as_deref(),
                reference: false,
                signoff: signoff > 0,
                edit: edit > 0,
                no_edit: false,
                cleanup: cleanup.as_deref(),
                rerere_autoupdate: rerere_autoupdate > 0,
                no_rerere_autoupdate: no_rerere_autoupdate > 0,
                strategy: strategy.as_deref(),
                strategy_option,
                gpg_sign,
                no_gpg_sign,
                commits,
            },
        ),
        runtime::Command::Revert {
            abort,
            continue_,
            no_commit,
            mainline,
            reference,
            signoff,
            edit,
            no_edit,
            cleanup,
            rerere_autoupdate,
            no_rerere_autoupdate,
            strategy,
            strategy_option,
            gpg_sign,
            no_gpg_sign,
            commits,
            ..
        } => super::sequencer_commands::sequencer_command(
            super::sequencer_commands::SequencerCommandOptions {
                command: "revert",
                abort,
                continue_,
                ff: false,
                no_commit,
                mainline,
                record_origin: false,
                allow_empty: false,
                allow_empty_message: false,
                keep_redundant_commits: false,
                empty: None,
                reference: reference > 0,
                signoff: signoff > 0,
                edit: edit > 0,
                no_edit: no_edit > 0,
                cleanup: cleanup.as_deref(),
                rerere_autoupdate: rerere_autoupdate > 0,
                no_rerere_autoupdate: no_rerere_autoupdate > 0,
                strategy: strategy.as_deref(),
                strategy_option,
                gpg_sign,
                no_gpg_sign,
                commits,
            },
        ),
        runtime::Command::Bisect { args } => super::sequencer_commands::bisect(args),
        runtime::Command::Rerere { args } => super::sequencer_commands::rerere(args),
        runtime::Command::Rebase {
            abort,
            continue_,
            interactive,
            merge: _merge,
            no_stat: _no_stat,
            onto,
            quiet,
            args,
        } => super::sequencer_commands::rebase(
            abort,
            continue_,
            onto.as_deref(),
            args,
            false,
            interactive,
            quiet,
        ),
        _ => unreachable!("non-sequencer command dispatched to sequencer"),
    }
}
