use crate::runtime;

pub(crate) fn dispatch(
    command: runtime::Command,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Clone {
            quiet,
            verbose: _verbose,
            progress: _progress,
            no_progress: _no_progress,
            bare,
            mirror,
            local: _local,
            no_local,
            no_hardlinks,
            hardlinks,
            reject_shallow,
            no_reject_shallow,
            template,
            no_template,
            configs,
            no_checkout,
            checkout,
            worktree_first,
            instant,
            background_fetch,
            demand_hydrate,
            recurse_submodules,
            recursive,
            no_recurse_submodules,
            jobs,
            shallow_submodules,
            remote_submodules,
            origin,
            no_tags,
            tags,
            single_branch,
            no_single_branch,
            separate_git_dir,
            references,
            reference_if_able,
            shared,
            dissociate,
            depth,
            branch,
            ref_format,
            repository,
            directory,
        } => run_clone(
            super::transport_commands::CloneCommandInput {
                quiet,
                reject_shallow,
                no_reject_shallow,
                template,
                no_template,
                configs,
                no_checkout,
                checkout,
                worktree_first,
                instant,
                background_fetch,
                demand_hydrate,
                recurse_submodules,
                recursive,
                no_recurse_submodules,
                jobs,
                shallow_submodules,
                remote_submodules,
                origin,
                no_tags,
                tags,
                single_branch,
                no_single_branch,
                separate_git_dir,
                references,
                reference_if_able,
                shared,
                dissociate,
                no_hardlinks,
                hardlinks,
                no_local,
                depth,
                branch,
                ref_format,
                repository,
                directory,
                bare,
                mirror,
            },
            raw_args,
        ),
        runtime::Command::LsRemote {
            heads,
            tags,
            refs_only,
            upload_pack: _,
            repository,
            patterns,
        } => run_ls_remote(heads, tags, refs_only, repository, patterns),
        runtime::Command::Fetch {
            all,
            multiple,
            prefetch,
            quiet,
            verbose,
            dry_run,
            force,
            set_upstream,
            append,
            prune,
            no_prune,
            prune_tags,
            no_tags,
            tags,
            atomic,
            recurse_submodules: _,
            no_recurse_submodules: _,
            update_head_ok,
            write_fetch_head,
            no_write_fetch_head,
            refmap,
            depth,
            negotiation_tip,
            negotiate_only,
            stdin,
            remote,
            branch: refspecs,
        } => run_fetch(
            all,
            multiple,
            prefetch,
            quiet,
            verbose,
            dry_run,
            force,
            set_upstream,
            append,
            prune,
            no_prune,
            prune_tags,
            no_tags,
            tags,
            atomic,
            update_head_ok,
            !no_write_fetch_head || write_fetch_head,
            refmap,
            depth,
            negotiation_tip,
            negotiate_only,
            stdin,
            remote,
            refspecs,
            raw_args,
        ),
        runtime::Command::Pull {
            ff_only,
            strategies,
            rebase,
            no_rebase,
            remote,
            branch,
        } => run_pull(ff_only, strategies, rebase, no_rebase, remote, branch),
        runtime::Command::Push {
            force,
            set_upstream,
            remote,
            refspecs,
        } => run_push(force, set_upstream, remote, refspecs),
        runtime::Command::Daemon {
            verbose,
            export_all,
            timeout,
            init_timeout,
            max_connections,
            strict_paths,
            base_path,
            base_path_relaxed,
            reuseaddr,
            pid_file,
            inetd,
            listen,
            port,
            directories,
        } => super::transport_commands::daemon(super::transport_commands::DaemonOptions {
            verbose,
            export_all,
            timeout,
            init_timeout,
            max_connections,
            strict_paths,
            base_path,
            base_path_relaxed,
            reuseaddr,
            pid_file,
            inetd,
            listen,
            port,
            directories,
        }),
        runtime::Command::UploadPack {
            strict,
            no_strict,
            stateless_rpc,
            advertise_refs,
            timeout,
            directory,
        } => super::transport_commands::upload_pack(super::transport_commands::UploadPackOptions {
            strict,
            no_strict,
            stateless_rpc,
            advertise_refs,
            timeout,
            directory,
        }),
        runtime::Command::HttpFetch {
            commit,
            tags,
            all,
            verbose,
            recover,
            write_ref,
            stdin,
            packfile,
            index_pack_args,
            args,
        } => super::transport_commands::http_fetch(super::transport_commands::HttpFetchOptions {
            commit,
            tags,
            all,
            verbose,
            recover,
            write_ref,
            stdin,
            packfile,
            index_pack_args,
            args,
        }),
        runtime::Command::HttpPush {
            all,
            dry_run,
            force,
            verbose,
            remote,
            heads,
        } => super::transport_commands::http_push(super::transport_commands::HttpPushOptions {
            all,
            dry_run,
            force,
            verbose,
            remote,
            heads,
        }),
        runtime::Command::FetchPack {
            all,
            stdin,
            quiet,
            keep,
            thin,
            include_tag,
            upload_pack,
            depth,
            no_progress,
            diag_url,
            verbose,
            directory,
            refs,
        } => super::transport_commands::fetch_pack(super::transport_commands::FetchPackOptions {
            all,
            stdin,
            quiet,
            keep,
            thin,
            include_tag,
            upload_pack,
            depth,
            no_progress,
            diag_url,
            verbose,
            directory,
            refs,
        }),
        runtime::Command::SendPack {
            mirror,
            dry_run,
            force,
            receive_pack,
            verbose,
            thin,
            atomic,
            all,
            stdin,
            directory,
            refs,
        } => super::transport_commands::send_pack(super::transport_commands::SendPackOptions {
            mirror,
            dry_run,
            force,
            receive_pack,
            verbose,
            thin,
            atomic,
            all,
            stdin,
            directory,
            refs,
        }),
        runtime::Command::HttpBackend => super::transport_commands::http_backend(),
        runtime::Command::ReceivePack { quiet, directory } => {
            super::transport_commands::receive_pack(quiet, directory)
        }
        runtime::Command::Shell { command, args } => {
            super::transport_commands::shell(command, args)
        }
        _ => unreachable!("non-transport command dispatched to transport"),
    }
}

pub(crate) fn run_clone(
    input: super::transport_commands::CloneCommandInput,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    super::transport_commands::run_clone(input, raw_args)
}

pub(crate) fn run_ls_remote(
    heads: bool,
    tags: bool,
    refs_only: bool,
    repository: Option<String>,
    patterns: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::transport_commands::run_ls_remote(heads, tags, refs_only, repository, patterns)
}

pub(crate) fn run_fetch(
    all: bool,
    multiple: bool,
    prefetch: bool,
    quiet: bool,
    verbose: bool,
    dry_run: bool,
    force: bool,
    set_upstream: bool,
    append: bool,
    prune: bool,
    no_prune: bool,
    prune_tags: bool,
    no_tags: bool,
    tags: bool,
    atomic: bool,
    update_head_ok: bool,
    write_fetch_head: bool,
    refmap: Vec<String>,
    depth: Option<String>,
    negotiation_tip: Vec<String>,
    negotiate_only: bool,
    stdin: bool,
    remote: Option<String>,
    refspecs: Vec<String>,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    super::transport_commands::run_fetch(
        all,
        multiple,
        prefetch,
        quiet,
        verbose,
        dry_run,
        force,
        set_upstream,
        append,
        prune,
        no_prune,
        prune_tags,
        no_tags,
        tags,
        atomic,
        update_head_ok,
        write_fetch_head,
        refmap,
        depth,
        negotiation_tip,
        negotiate_only,
        stdin,
        remote,
        refspecs,
        raw_args,
    )
}

pub(crate) fn run_pull(
    ff_only: bool,
    strategies: Vec<String>,
    rebase_mode: Option<String>,
    no_rebase: bool,
    remote: Option<String>,
    branch: Option<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::transport_commands::run_pull(ff_only, strategies, rebase_mode, no_rebase, remote, branch)
}

pub(crate) fn run_push(
    force: bool,
    set_upstream: bool,
    remote: Option<String>,
    refspecs: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::transport_commands::run_push(force, set_upstream, remote, refspecs)
}
