use crate::runtime;

pub(crate) fn dispatch(
    command: runtime::Command,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::Clone {
            quiet,
            verbose: _verbose,
            progress: _progress,
            no_progress: _no_progress,
            bare,
            mirror,
            local: _local,
            no_local,
            no_hardlinks,
            hardlinks,
            reject_shallow,
            no_reject_shallow,
            template,
            no_template,
            configs,
            no_checkout,
            checkout,
            worktree_first,
            instant,
            background_fetch,
            demand_hydrate,
            recurse_submodules,
            recursive,
            no_recurse_submodules,
            jobs,
            shallow_submodules,
            remote_submodules,
            origin,
            no_tags,
            tags,
            single_branch,
            no_single_branch,
            separate_git_dir,
            references,
            reference_if_able,
            shared,
            dissociate,
            depth,
            branch,
            ref_format,
            repository,
            directory,
        } => run_clone(
            super::transport_commands::CloneCommandInput {
                quiet,
                reject_shallow,
                no_reject_shallow,
                template,
                no_template,
                configs,
                no_checkout,
                checkout,
                worktree_first,
                instant,
                background_fetch,
                demand_hydrate,
                recurse_submodules,
                recursive,
                no_recurse_submodules,
                jobs,
                shallow_submodules,
                remote_submodules,
                origin,
                no_tags,
                tags,
                single_branch,
                no_single_branch,
                separate_git_dir,
                references,
                reference_if_able,
                shared,
                dissociate,
                no_hardlinks,
                hardlinks,
                no_local,
                depth,
                branch,
                ref_format,
                repository,
                directory,
                bare,
                mirror,
            },
            raw_args,
        ),
        runtime::Command::LsRemote {
            heads,
            tags,
            refs_only,
            upload_pack,
            repository,
            patterns,
        } => run_ls_remote(heads, tags, refs_only, upload_pack, repository, patterns),
        runtime::Command::Fetch {
            all,
            no_all: _,
            multiple,
            prefetch,
            quiet,
            verbose,
            progress: _,
            dry_run,
            force,
            auto_gc: _,
            auto_maintenance: _,
            no_auto_gc: _,
            no_auto_maintenance: _,
            set_upstream,
            append,
            prune,
            no_prune,
            prune_tags,
            no_tags,
            tags,
            atomic,
            keep: _,
            ipv4: _,
            ipv6: _,
            recurse_submodules: _,
            no_recurse_submodules: _,
            jobs: _,
            update_head_ok,
            write_fetch_head,
            no_write_fetch_head,
            write_commit_graph: _,
            no_write_commit_graph: _,
            refmap,
            depth,
            deepen: _,
            unshallow,
            update_shallow,
            shallow_since: _,
            shallow_exclude: _,
            negotiation_tip,
            negotiate_only,
            server_option: _,
            show_forced_updates: _,
            no_show_forced_updates: _,
            upload_pack: _,
            filter,
            stdin,
            porcelain,
            recurse_submodules_default: _,
            refetch: _,
            submodule_prefix: _,
            remote,
            branch: refspecs,
        } => run_fetch(
            all,
            multiple,
            prefetch,
            quiet,
            verbose,
            dry_run,
            force,
            set_upstream,
            append,
            prune,
            no_prune,
            prune_tags,
            no_tags,
            tags,
            atomic,
            update_head_ok,
            !no_write_fetch_head || write_fetch_head,
            refmap,
            depth,
            unshallow,
            update_shallow,
            negotiation_tip,
            negotiate_only,
            filter,
            stdin,
            porcelain,
            remote,
            refspecs,
            raw_args,
        ),
        runtime::Command::Pull {
            all,
            no_all,
            verbose: _,
            prune,
            no_tags,
            tags,
            jobs: _,
            keep: _,
            ipv4: _,
            ipv6: _,
            recurse_submodules: _,
            no_recurse_submodules: _,
            server_option: _,
            show_forced_updates: _,
            no_show_forced_updates: _,
            ff,
            ff_only,
            no_ff,
            stat,
            no_stat,
            summary,
            no_summary,
            commit,
            no_commit,
            log,
            no_log,
            squash,
            no_squash,
            edit,
            no_edit,
            autostash,
            no_autostash,
            cleanup,
            signoff,
            no_signoff,
            gpg_sign,
            no_gpg_sign,
            verify,
            no_verify,
            verify_signatures,
            no_verify_signatures,
            quiet,
            progress,
            no_progress,
            allow_unrelated_histories,
            strategies,
            strategy_options,
            rebase,
            no_rebase,
            depth,
            deepen,
            unshallow,
            update_shallow,
            shallow_since,
            shallow_exclude,
            upload_pack,
            remote,
            branch,
        } => run_pull(
            all,
            ff,
            ff_only,
            no_ff,
            stat,
            no_stat,
            summary,
            no_summary,
            commit,
            no_commit,
            log,
            no_log,
            squash,
            no_squash,
            edit,
            no_edit,
            autostash,
            no_autostash,
            cleanup,
            signoff,
            no_signoff,
            gpg_sign,
            no_gpg_sign,
            verify,
            no_verify,
            verify_signatures,
            no_verify_signatures,
            quiet,
            progress,
            no_progress,
            allow_unrelated_histories,
            no_all,
            prune,
            no_tags,
            tags,
            strategies,
            strategy_options,
            rebase,
            no_rebase,
            depth,
            deepen,
            unshallow,
            update_shallow,
            shallow_since,
            shallow_exclude,
            upload_pack,
            remote,
            branch,
            raw_args,
        ),
        runtime::Command::Push {
            force,
            set_upstream,
            remote,
            refspecs,
        } => run_push(force, set_upstream, remote, refspecs),
        runtime::Command::Daemon {
            verbose,
            export_all,
            timeout,
            init_timeout,
            max_connections,
            strict_paths,
            base_path,
            base_path_relaxed,
            reuseaddr,
            pid_file,
            inetd,
            listen,
            port,
            directories,
        } => super::transport_commands::daemon(super::transport_commands::DaemonOptions {
            verbose,
            export_all,
            timeout,
            init_timeout,
            max_connections,
            strict_paths,
            base_path,
            base_path_relaxed,
            reuseaddr,
            pid_file,
            inetd,
            listen,
            port,
            directories,
        }),
        runtime::Command::UploadPack {
            strict,
            no_strict,
            stateless_rpc,
            http_backend_info_refs,
            advertise_refs,
            timeout,
            directory,
        } => super::transport_commands::upload_pack(super::transport_commands::UploadPackOptions {
            strict,
            no_strict,
            stateless_rpc,
            advertise_refs: advertise_refs || http_backend_info_refs,
            timeout,
            directory,
        }),
        runtime::Command::HttpFetch {
            commit,
            tags,
            all,
            verbose,
            recover,
            write_ref,
            stdin,
            packfile,
            index_pack_args,
            index_pack_args_plural: _,
            args,
        } => super::transport_commands::http_fetch(super::transport_commands::HttpFetchOptions {
            commit,
            tags,
            all,
            verbose,
            recover,
            write_ref,
            stdin,
            packfile,
            index_pack_args,
            args,
        }),
        runtime::Command::HttpPush {
            all,
            dry_run,
            delete,
            force_delete,
            force,
            verbose,
            remote,
            heads,
        } => super::transport_commands::http_push(super::transport_commands::HttpPushOptions {
            all,
            dry_run,
            delete,
            force_delete,
            force,
            verbose,
            remote,
            heads,
        }),
        runtime::Command::FetchPack {
            all,
            stdin,
            quiet,
            keep,
            thin,
            include_tag,
            exec,
            upload_pack,
            depth,
            shallow_since,
            shallow_exclude,
            deepen_relative,
            refetch,
            check_self_contained_and_connected,
            no_progress,
            diag_url,
            verbose,
            directory,
            refs,
        } => super::transport_commands::fetch_pack(super::transport_commands::FetchPackOptions {
            all,
            stdin,
            quiet,
            keep,
            thin,
            include_tag,
            exec,
            upload_pack,
            depth,
            shallow_since,
            shallow_exclude,
            deepen_relative,
            refetch,
            check_self_contained_and_connected,
            no_progress,
            diag_url,
            verbose,
            directory,
            refs,
        }),
        runtime::Command::SendPack {
            mirror,
            dry_run,
            force,
            receive_pack,
            exec,
            verbose,
            thin,
            atomic,
            signed,
            no_signed,
            push_option,
            all,
            stdin,
            directory,
            refs,
        } => super::transport_commands::send_pack(super::transport_commands::SendPackOptions {
            mirror,
            dry_run,
            force,
            receive_pack,
            exec,
            verbose,
            thin,
            atomic,
            signed,
            no_signed,
            push_option,
            all,
            stdin,
            directory,
            refs,
        }),
        runtime::Command::HttpBackend => super::transport_commands::http_backend(),
        runtime::Command::ReceivePack {
            http_backend_info_refs,
            quiet,
            directory,
        } => super::transport_commands::receive_pack(http_backend_info_refs, quiet, directory),

        runtime::Command::Shell { command, args } => {
            super::transport_commands::shell(command, args)
        }
        _ => unreachable!("non-transport command dispatched to transport"),
    }
}

pub(crate) fn run_clone(
    input: super::transport_commands::CloneCommandInput,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    super::transport_commands::run_clone(input, raw_args)
}

pub(crate) fn run_ls_remote(
    heads: bool,
    tags: bool,
    refs_only: bool,
    upload_pack: Option<String>,
    repository: Option<String>,
    patterns: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::transport_commands::run_ls_remote(
        heads,
        tags,
        refs_only,
        upload_pack,
        repository,
        patterns,
    )
}

pub(crate) fn run_fetch(
    all: bool,
    multiple: bool,
    prefetch: bool,
    quiet: bool,
    verbose: bool,
    dry_run: bool,
    force: bool,
    set_upstream: bool,
    append: bool,
    prune: bool,
    no_prune: bool,
    prune_tags: bool,
    no_tags: bool,
    tags: bool,
    atomic: bool,
    update_head_ok: bool,
    write_fetch_head: bool,
    refmap: Vec<String>,
    depth: Option<String>,
    unshallow: bool,
    update_shallow: bool,
    negotiation_tip: Vec<String>,
    negotiate_only: bool,
    filter: Option<String>,
    stdin: bool,
    porcelain: bool,
    remote: Option<String>,
    refspecs: Vec<String>,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    super::transport_commands::run_fetch(
        all,
        multiple,
        prefetch,
        quiet,
        verbose,
        dry_run,
        force,
        set_upstream,
        append,
        prune,
        no_prune,
        prune_tags,
        no_tags,
        tags,
        atomic,
        update_head_ok,
        write_fetch_head,
        refmap,
        depth,
        unshallow,
        update_shallow,
        negotiation_tip,
        negotiate_only,
        filter,
        stdin,
        porcelain,
        remote,
        refspecs,
        raw_args,
    )
}

pub(crate) fn run_pull(
    all: bool,
    ff: bool,
    ff_only: bool,
    no_ff: bool,
    stat: bool,
    no_stat: bool,
    summary: bool,
    no_summary: bool,
    commit: bool,
    no_commit: bool,
    log: Option<String>,
    no_log: bool,
    squash: bool,
    no_squash: bool,
    edit: u8,
    no_edit: u8,
    autostash: bool,
    no_autostash: bool,
    cleanup: Option<String>,
    signoff: u8,
    no_signoff: u8,
    gpg_sign: Option<String>,
    no_gpg_sign: u8,
    verify: u8,
    no_verify: u8,
    verify_signatures: u8,
    no_verify_signatures: u8,
    quiet: bool,
    progress: u8,
    no_progress: u8,
    allow_unrelated_histories: bool,
    no_all: bool,
    prune: bool,
    no_tags: bool,
    tags: bool,
    strategies: Vec<String>,
    strategy_options: Vec<String>,
    rebase_mode: Option<String>,
    no_rebase: bool,
    depth: Option<String>,
    deepen: Option<String>,
    unshallow: bool,
    update_shallow: bool,
    shallow_since: Option<String>,
    shallow_exclude: Vec<String>,
    upload_pack: Option<String>,
    remote: Option<String>,
    branch: Option<String>,
    raw_args: &[String],
) -> std::result::Result<(), runtime::CliError> {
    super::transport_commands::run_pull(
        all,
        ff,
        ff_only,
        no_ff,
        stat,
        no_stat,
        summary,
        no_summary,
        commit,
        no_commit,
        log,
        no_log,
        squash,
        no_squash,
        edit,
        no_edit,
        autostash,
        no_autostash,
        cleanup,
        signoff,
        no_signoff,
        gpg_sign,
        no_gpg_sign,
        verify,
        no_verify,
        verify_signatures,
        no_verify_signatures,
        quiet,
        progress,
        no_progress,
        allow_unrelated_histories,
        no_all,
        prune,
        no_tags,
        tags,
        strategies,
        strategy_options,
        rebase_mode,
        no_rebase,
        depth,
        deepen,
        unshallow,
        update_shallow,
        shallow_since,
        shallow_exclude,
        upload_pack,
        remote,
        branch,
        raw_args,
    )
}

pub(crate) fn run_push(
    force: bool,
    set_upstream: bool,
    remote: Option<String>,
    refspecs: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::transport_commands::run_push(force, set_upstream, remote, refspecs)
}
