use crate::runtime;
use std::path::PathBuf;

pub(crate) fn dispatch(command: runtime::Command) -> std::result::Result<(), runtime::CliError> {
    match command {
        runtime::Command::LsFiles {
            cached,
            zero,
            full_name,
            error_unmatch,
            tagged,
            lowercase_assume_valid,
            fsmonitor_clean,
            deduplicate,
            sparse,
            recurse_submodules,
            no_recurse_submodules,
            debug,
            abbrev,
            eol,
            format,
            with_tree,
            resolve_undo,
            stage,
            unmerged,
            deleted,
            modified,
            others,
            killed,
            directory,
            empty_directory,
            no_empty_directory,
            ignored,
            excludes,
            exclude_from,
            exclude_per_directory,
            exclude_standard,
            paths,
        } => run_ls_files(runtime::LsFilesOptions {
            cached,
            stage,
            unmerged,
            deleted,
            modified,
            others,
            killed,
            directory,
            empty_directory,
            no_empty_directory,
            ignored,
            excludes,
            exclude_from,
            exclude_per_directory,
            exclude_standard,
            zero,
            full_name,
            error_unmatch,
            tagged,
            lowercase_assume_valid,
            fsmonitor_clean,
            deduplicate,
            sparse,
            recurse_submodules,
            no_recurse_submodules,
            debug,
            abbrev,
            eol,
            format,
            with_tree,
            resolve_undo,
            path_args: paths,
        }),
        runtime::Command::Add {
            all,
            ignore_removal: _,
            no_ignore_removal,
            force,
            update,
            no_update: _,
            renormalize,
            no_renormalize: _,
            intent_to_add,
            no_intent_to_add: _,
            refresh,
            no_refresh: _,
            verbose,
            no_verbose: _,
            ignore_errors,
            no_ignore_errors: _,
            ignore_missing,
            no_ignore_missing: _,
            sparse: _,
            no_sparse: _,
            no_warn_embedded_repo,
            interactive,
            patch,
            edit,
            chmod,
            no_chmod: _,
            dry_run,
            no_dry_run: _,
            pathspec_from_file,
            no_pathspec_from_file: _,
            pathspec_file_nul,
            no_pathspec_file_nul: _,
            paths,
        }
        | runtime::Command::Stage {
            all,
            ignore_removal: _,
            no_ignore_removal,
            force,
            update,
            no_update: _,
            renormalize,
            no_renormalize: _,
            intent_to_add,
            no_intent_to_add: _,
            refresh,
            no_refresh: _,
            verbose,
            no_verbose: _,
            ignore_errors,
            no_ignore_errors: _,
            ignore_missing,
            no_ignore_missing: _,
            sparse: _,
            no_sparse: _,
            no_warn_embedded_repo,
            interactive,
            patch,
            edit,
            chmod,
            no_chmod: _,
            dry_run,
            no_dry_run: _,
            pathspec_from_file,
            no_pathspec_from_file: _,
            pathspec_file_nul,
            no_pathspec_file_nul: _,
            paths,
        } => run_add(
            all > 0 || no_ignore_removal > 0,
            force > 0,
            update > 0 || renormalize > 0,
            intent_to_add > 0,
            refresh > 0,
            verbose > 0,
            ignore_errors > 0,
            ignore_missing > 0,
            no_warn_embedded_repo > 0,
            interactive > 0,
            patch > 0,
            edit > 0,
            chmod.last().cloned(),
            dry_run > 0,
            pathspec_from_file,
            pathspec_file_nul > 0,
            paths,
        ),
        runtime::Command::Rm {
            force,
            no_force: _,
            dry_run,
            no_dry_run: _,
            quiet,
            no_quiet: _,
            recursive,
            cached,
            no_cached: _,
            ignore_unmatch,
            no_ignore_unmatch: _,
            sparse,
            no_sparse: _,
            pathspec_from_file,
            pathspec_file_nul,
            no_pathspec_file_nul: _,
            paths,
        } => run_rm(runtime::RmOptions {
            force: force > 0,
            dry_run: dry_run > 0,
            quiet: quiet > 0,
            recursive: recursive > 0,
            cached: cached > 0,
            ignore_unmatch: ignore_unmatch > 0,
            sparse: sparse > 0,
            pathspec_from_file,
            pathspec_file_nul: pathspec_file_nul > 0,
            paths,
        }),
        runtime::Command::Mv {
            force,
            no_force: _,
            dry_run,
            no_dry_run: _,
            verbose,
            no_verbose: _,
            skip_errors,
            sparse: _,
            no_sparse: _,
            paths,
        } => run_mv(force > 0, dry_run > 0, verbose > 0, skip_errors > 0, paths),
        runtime::Command::Status {
            porcelain,
            branch,
            no_branch,
            ahead_behind: _,
            no_ahead_behind,
            show_stash,
            no_show_stash,
            verbose,
            no_verbose,
            long: _,
            no_long: _,
            column,
            no_column,
            renames: _,
            no_renames,
            find_renames: _,
            ignore_submodules,
            untracked_cache,
            no_untracked_cache,
            split_index,
            no_split_index,
            short,
            null,
            ignored,
            untracked_files,
            paths,
        } => {
            for (enabled, option) in [
                (untracked_cache, "untracked-cache"),
                (no_untracked_cache, "no-untracked-cache"),
                (split_index, "split-index"),
                (no_split_index, "no-split-index"),
            ] {
                if enabled {
                    return Err(runtime::CliError::Stderr {
                        code: 129,
                        text: format!("error: unknown option `{option}`\n"),
                    });
                }
            }
            run_status(
                porcelain,
                branch && !no_branch,
                !no_ahead_behind,
                show_stash && !no_show_stash,
                if no_verbose { 0 } else { verbose },
                column,
                no_column,
                !no_renames,
                ignore_submodules,
                short,
                null,
                ignored,
                untracked_files,
                paths,
            )
        }
        runtime::Command::ReadTree {
            empty,
            merge,
            trivial,
            aggressive,
            reset,
            update_worktree,
            index_only,
            dry_run,
            verbose,
            quiet,
            index_output,
            prefix,
            recurse_submodules,
            no_recurse_submodules,
            no_sparse_checkout,
            treeish,
        } => run_read_tree(
            empty > 0,
            merge,
            trivial > 0,
            aggressive > 0,
            reset > 0,
            update_worktree > 0,
            index_only > 0,
            dry_run,
            verbose,
            quiet,
            index_output.last().cloned(),
            prefix,
            recurse_submodules > 0,
            no_recurse_submodules > 0,
            no_sparse_checkout > 0,
            treeish,
        ),
        runtime::Command::Checkout {
            force,
            quiet,
            no_progress,
            detach,
            recurse_submodules,
            no_recurse_submodules,
            create,
            reset_create,
            create_reflog,
            orphan,
            args,
        } => super::worktree_commands::checkout(
            force,
            quiet,
            no_progress,
            detach,
            recurse_submodules,
            no_recurse_submodules,
            create,
            reset_create,
            create_reflog,
            orphan,
            args,
        ),
        runtime::Command::CheckoutIndex {
            all,
            force,
            quiet,
            index,
            no_create,
            stage,
            temp,
            ignore_skip_worktree_bits,
            stdin,
            nul,
            prefix,
            paths,
        } => run_checkout_index(super::worktree_commands::CheckoutIndexCommandOptions {
            all: all > 0,
            force: force > 0,
            quiet: quiet > 0,
            update_index: index > 0,
            no_create: no_create > 0,
            stage,
            temp,
            ignore_skip_worktree_bits,
            stdin,
            nul,
            prefix,
            paths,
        }),
        runtime::Command::Switch {
            force,
            discard_changes,
            create,
            orphan,
            detach,
            target,
        } => {
            super::worktree_commands::switch(force, discard_changes, create, orphan, detach, target)
        }
        runtime::Command::Restore {
            source,
            staged,
            no_staged,
            worktree,
            no_worktree,
            no_overlay: _,
            paths,
        } => run_restore(
            source.into_iter().next_back(),
            staged > 0,
            no_staged,
            worktree > 0,
            no_worktree,
            paths,
        ),
        runtime::Command::Clean { args } => run_clean(args),
        runtime::Command::Reset {
            soft,
            mixed,
            hard,
            args,
        } => run_reset(soft, mixed, hard, args),
        runtime::Command::Stash { args } => run_stash(args),
        runtime::Command::Worktree { args } => run_worktree(args),
        runtime::Command::SparseCheckout { args } => run_sparse_checkout(args),
        runtime::Command::Submodule { args } => run_submodule(args),
        _ => unreachable!("non-worktree command dispatched to worktree"),
    }
}

pub(crate) fn run_ls_files(
    options: runtime::LsFilesOptions,
) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::ls_files(options)
}

pub(crate) fn run_add(
    all: bool,
    force: bool,
    update: bool,
    intent_to_add: bool,
    refresh: bool,
    verbose: bool,
    ignore_errors: bool,
    ignore_missing: bool,
    no_warn_embedded_repo: bool,
    interactive: bool,
    patch: bool,
    edit: bool,
    chmod: Option<String>,
    dry_run: bool,
    pathspec_from_file: Option<PathBuf>,
    pathspec_file_nul: bool,
    paths: Vec<PathBuf>,
) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::add_with_embedded_repo_warning(
        all,
        force,
        update,
        intent_to_add,
        refresh,
        verbose,
        ignore_errors,
        ignore_missing,
        no_warn_embedded_repo,
        interactive,
        patch,
        edit,
        chmod,
        dry_run,
        pathspec_from_file,
        pathspec_file_nul,
        paths,
    )
}

pub(crate) fn run_rm(options: runtime::RmOptions) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::rm(options)
}

pub(crate) fn run_mv(
    force: bool,
    dry_run: bool,
    verbose: bool,
    skip_errors: bool,
    paths: Vec<PathBuf>,
) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::mv(force, dry_run, verbose, skip_errors, paths)
}

pub(crate) fn run_status(
    porcelain: Option<String>,
    branch: bool,
    ahead_behind: bool,
    show_stash: bool,
    verbose: u8,
    column: Option<String>,
    no_column: bool,
    detect_renames: bool,
    ignore_submodules: Option<String>,
    short: bool,
    null: bool,
    ignored: Option<String>,
    untracked_files: Option<String>,
    paths: Vec<PathBuf>,
) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::status(
        porcelain.as_deref(),
        branch,
        ahead_behind,
        show_stash,
        verbose,
        column.as_deref(),
        no_column,
        detect_renames,
        ignore_submodules.as_deref(),
        short,
        null,
        ignored.as_deref(),
        untracked_files.as_deref(),
        paths,
    )
}

pub(crate) fn run_read_tree(
    empty: bool,
    merge: u8,
    trivial: bool,
    aggressive: bool,
    reset: bool,
    update_worktree: bool,
    index_only: bool,
    dry_run: u8,
    verbose: u8,
    quiet: u8,
    index_output: Option<PathBuf>,
    prefix: Option<String>,
    recurse_submodules: bool,
    no_recurse_submodules: bool,
    no_sparse_checkout: bool,
    treeish: Option<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::read_tree_command(super::worktree_commands::ReadTreeCommandOptions {
        empty,
        merge: merge > 0,
        trivial,
        aggressive,
        reset,
        update_worktree,
        index_only,
        dry_run: dry_run > 0,
        verbose: verbose > 0,
        quiet: quiet > 0,
        index_output,
        prefix,
        recurse_submodules,
        no_recurse_submodules,
        no_sparse_checkout,
        treeish,
    })
}

pub(crate) fn run_checkout_index(
    options: super::worktree_commands::CheckoutIndexCommandOptions,
) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::checkout_index_command(options)
}

pub(crate) fn run_restore(
    source: Option<String>,
    staged: bool,
    no_staged: bool,
    worktree: bool,
    no_worktree: bool,
    paths: Vec<PathBuf>,
) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::restore(
        source.as_deref(),
        staged,
        no_staged,
        worktree,
        no_worktree,
        paths,
    )
    .map(|_| ())
}

pub(crate) fn run_clean(args: Vec<String>) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::clean(args)
}

pub(crate) fn run_reset(
    soft: bool,
    mixed: bool,
    hard: bool,
    args: Vec<String>,
) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::reset(soft, mixed, hard, args)
}

pub(crate) fn run_stash(args: Vec<String>) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::stash(args)
}

pub(crate) fn run_worktree(args: Vec<String>) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::worktree(args)
}

pub(crate) fn run_sparse_checkout(args: Vec<String>) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::sparse_checkout(args)
}

pub(crate) fn run_submodule(args: Vec<String>) -> std::result::Result<(), runtime::CliError> {
    super::worktree_commands::submodule(args)
}
